// Real-World Indian Electricity Demand Sinks: Cities, Heavy Industrial Factories, Residential Housing & Critical Infrastructure
// Sourced from DISCOM Load Curves, CEA Power Supply Position Reports, State GIDC & Urban Development Authorities.

export const ELECTRICITY_SINKS = [
  {
    "id": "SNK-DELHI",
    "name": "Delhi-NCR Megacity & Commercial Hub",
    "category": "CITY_METRO",
    "city": "National Capital Region (Delhi/Noida/Gurugram)",
    "state": "Delhi & NCR",
    "coordinates": [
      28.61,
      77.23
    ],
    "region": "NR",
    "peakDemandMw": 8656,
    "baseDemandMw": 7420,
    "currentDemandMw": 7420,
    "loadShedPct": 0,
    "voltageLevelKv": 66,
    "connectedSubstation": "Mayur Vihar 66/11kV Substation & Bawana 400kV",
    "discomOperator": "BSES Yamuna / BSES Rajdhani / TPDDL / DTL",
    "operator": "BSES Yamuna / BSES Rajdhani / TPDDL / DTL",
    "description": "Highest peak load density in Northern Grid. Record peak demand exceeding 8656 MW during summer heatwaves with extreme air-conditioning load swings.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_CRITICAL"
  },
  {
    "id": "SNK-MUMBAI",
    "name": "Mumbai Metropolitan Region (MMR)",
    "category": "CITY_METRO",
    "city": "Mumbai / Thane / Navi Mumbai",
    "state": "Maharashtra",
    "coordinates": [
      19.07,
      72.87
    ],
    "region": "WR",
    "peakDemandMw": 4300,
    "baseDemandMw": 3850,
    "currentDemandMw": 3850,
    "loadShedPct": 0,
    "voltageLevelKv": 220,
    "connectedSubstation": "Kalwa 400/220kV Receiving Station & Trombay",
    "discomOperator": "Adani Electricity Mumbai / Tata Power / BEST / MSEDCL",
    "operator": "Adani Electricity Mumbai / Tata Power / BEST / MSEDCL",
    "description": "Financial capital hub supplied by Western Grid transmission lines and protected by an automated islanding scheme preventing blackout cascades.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_CRITICAL"
  },
  {
    "id": "SNK-BLR",
    "name": "Bengaluru Tech & Electronics City Belt",
    "category": "CITY_METRO",
    "city": "Bengaluru Urban",
    "state": "Karnataka",
    "coordinates": [
      12.97,
      77.59
    ],
    "region": "SR",
    "peakDemandMw": 3450,
    "baseDemandMw": 3120,
    "currentDemandMw": 3120,
    "loadShedPct": 0,
    "voltageLevelKv": 220,
    "connectedSubstation": "Hoodi 400/220kV Substation & Nelamangala",
    "discomOperator": "BESCOM (Bangalore Electricity Supply Company)",
    "operator": "BESCOM (Bangalore Electricity Supply Company)",
    "description": "High-density technology corridor powering Electronic City Whitefield tech campuses semiconductor R&D and aerospace engineering clusters.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_CRITICAL"
  },
  {
    "id": "SNK-AHMEDABAD",
    "name": "Ahmedabad Urban Area",
    "category": "CITY_METRO",
    "city": "Ahmedabad & Gandhinagar",
    "state": "Gujarat",
    "coordinates": [
      23.02,
      72.57
    ],
    "region": "WR",
    "peakDemandMw": 2800,
    "baseDemandMw": 2480,
    "currentDemandMw": 2480,
    "loadShedPct": 0,
    "voltageLevelKv": 132,
    "connectedSubstation": "Pirana 400kV Substation & Sabarmati",
    "discomOperator": "Torrent Power Limited / UGVCL",
    "operator": "Torrent Power Limited / UGVCL",
    "description": "Commercial and administrative core of Gujarat including GIFT City International Financial Services Centre and Sabarmati high-voltage grid loop.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_CRITICAL"
  },
  {
    "id": "SNK-SURAT",
    "name": "Surat Textile & Diamond City",
    "category": "CITY_METRO",
    "city": "Surat",
    "state": "Gujarat",
    "coordinates": [
      21.17,
      72.83
    ],
    "region": "WR",
    "peakDemandMw": 2100,
    "baseDemandMw": 1850,
    "currentDemandMw": 1850,
    "loadShedPct": 0,
    "voltageLevelKv": 66,
    "connectedSubstation": "Ichhapore 220kV & Surat City Gas Turbine Receiving Station",
    "discomOperator": "Torrent Power Limited / DGVCL",
    "operator": "Torrent Power Limited / DGVCL",
    "description": "Global diamond polishing and synthetic textile manufacturing epicenter powered directly by Ukai Hydro Kakrapar Nuclear and Hazira corridors.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_2_COMMERCIAL"
  },
  {
    "id": "SNK-CHENNAI",
    "name": "Chennai Metropolitan Area",
    "category": "CITY_METRO",
    "city": "Chennai & Suburbs",
    "state": "Tamil Nadu",
    "coordinates": [
      13.08,
      80.27
    ],
    "region": "SR",
    "peakDemandMw": 3900,
    "baseDemandMw": 3510,
    "currentDemandMw": 3510,
    "loadShedPct": 0,
    "voltageLevelKv": 230,
    "connectedSubstation": "Sriperumbudur 400kV Substation & Alamathy",
    "discomOperator": "TANGEDCO",
    "operator": "TANGEDCO",
    "description": "Southern manufacturing hub automotive Detroit of India hyperscale submarine cable landing data centers and major container ports.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_CRITICAL"
  },
  {
    "id": "SNK-KOLKATA",
    "name": "Kolkata - Howrah Metropolitan Belt",
    "category": "CITY_METRO",
    "city": "Kolkata & Howrah",
    "state": "West Bengal",
    "coordinates": [
      22.57,
      88.36
    ],
    "region": "ER",
    "peakDemandMw": 2600,
    "baseDemandMw": 2250,
    "currentDemandMw": 2250,
    "loadShedPct": 0,
    "voltageLevelKv": 132,
    "connectedSubstation": "Subhashgram 400kV Substation & Titagarh",
    "discomOperator": "CESC Limited / WBSEDCL",
    "operator": "CESC Limited / WBSEDCL",
    "description": "Historic trade center of Eastern India with intensive underground electric grid network and East-West Metro underwater tunnel lines.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_CRITICAL"
  },
  {
    "id": "SNK-HYDERABAD",
    "name": "Hyderabad Cyberabad & HITEC City",
    "category": "CITY_METRO",
    "city": "Hyderabad & Secunderabad",
    "state": "Telangana",
    "coordinates": [
      17.38,
      78.48
    ],
    "region": "SR",
    "peakDemandMw": 3600,
    "baseDemandMw": 3150,
    "currentDemandMw": 3150,
    "loadShedPct": 0,
    "voltageLevelKv": 220,
    "connectedSubstation": "Gachibowli 400/220kV & Malkaram Substation",
    "discomOperator": "TSSPDCL",
    "operator": "TSSPDCL",
    "description": "Major pharmaceutical software and biotechnology hub with fast-growing residential and hyperscale cloud infrastructure demand.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_CRITICAL"
  },
  {
    "id": "SNK-PUNE",
    "name": "Pune Automobile & IT Hub",
    "category": "CITY_METRO",
    "city": "Pune & Pimpri-Chinchwad",
    "state": "Maharashtra",
    "coordinates": [
      18.52,
      73.85
    ],
    "region": "WR",
    "peakDemandMw": 2400,
    "baseDemandMw": 2100,
    "currentDemandMw": 2100,
    "loadShedPct": 0,
    "voltageLevelKv": 132,
    "connectedSubstation": "Chakan 400/220kV & Lonikand Substation",
    "discomOperator": "MSEDCL",
    "operator": "MSEDCL",
    "description": "Engineering capital and education center housing prominent automotive OEMs and Rajiv Gandhi Infotech Park at Hinjewadi.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_CRITICAL"
  },
  {
    "id": "SNK-JAIPUR",
    "name": "Jaipur Heritage & Industrial Hub",
    "category": "CITY_METRO",
    "city": "Jaipur Metropolitan Area",
    "state": "Rajasthan",
    "coordinates": [
      26.91,
      75.78
    ],
    "region": "NR",
    "peakDemandMw": 1850,
    "baseDemandMw": 1580,
    "currentDemandMw": 1580,
    "loadShedPct": 0,
    "voltageLevelKv": 132,
    "connectedSubstation": "Heerapura 400/220kV Grid Substation",
    "discomOperator": "JVVNL (Jaipur Vidyut Vitran Nigam)",
    "operator": "JVVNL (Jaipur Vidyut Vitran Nigam)",
    "description": "State capital and tourist economic center requiring reliable power wheeling from Rajasthan's mega solar and wind corridors.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_2_COMMERCIAL"
  },
  {
    "id": "SNK-LUCKNOW",
    "name": "Lucknow Urban & Administrative Corridor",
    "category": "CITY_METRO",
    "city": "Lucknow",
    "state": "Uttar Pradesh",
    "coordinates": [
      26.84,
      80.94
    ],
    "region": "NR",
    "peakDemandMw": 1950,
    "baseDemandMw": 1680,
    "currentDemandMw": 1680,
    "loadShedPct": 0,
    "voltageLevelKv": 132,
    "connectedSubstation": "Sarojini Nagar 220kV & Chinhat 132kV",
    "discomOperator": "MVVNL / UPPCL",
    "operator": "MVVNL / UPPCL",
    "description": "Northern administrative capital with expanding metro railway network defense industrial corridor and high domestic residential density.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_CRITICAL"
  },
  {
    "id": "SNK-BHOPAL",
    "name": "Bhopal Central Administrative City",
    "category": "CITY_METRO",
    "city": "Bhopal",
    "state": "Madhya Pradesh",
    "coordinates": [
      23.25,
      77.41
    ],
    "region": "WR",
    "peakDemandMw": 1100,
    "baseDemandMw": 940,
    "currentDemandMw": 940,
    "loadShedPct": 0,
    "voltageLevelKv": 132,
    "connectedSubstation": "Bhopal (Sukhi Sewaniya) 400/220kV Substation",
    "discomOperator": "MP Madhya Kshetra VVCL",
    "operator": "MP Madhya Kshetra VVCL",
    "description": "Administrative capital of central India linked to Vindhyachal thermal and Indira Sagar hydro dispatch channels.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_2_COMMERCIAL"
  },
  {
    "id": "SNK-PATNA",
    "name": "Patna Urban Core & Ganga Corridor",
    "category": "CITY_METRO",
    "city": "Patna",
    "state": "Bihar",
    "coordinates": [
      25.59,
      85.13
    ],
    "region": "ER",
    "peakDemandMw": 1250,
    "baseDemandMw": 1080,
    "currentDemandMw": 1080,
    "loadShedPct": 0,
    "voltageLevelKv": 132,
    "connectedSubstation": "Khagaul 220/132kV & Fatuha 220kV Substation",
    "discomOperator": "SBPDCL",
    "operator": "SBPDCL",
    "description": "Major commercial center along the Ganges river with rapid electrification of public services and Patna Metro construction.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_2_COMMERCIAL"
  },
  {
    "id": "SNK-BHUBANESWAR",
    "name": "Bhubaneswar-Cuttack Twin City Zone",
    "category": "CITY_METRO",
    "city": "Bhubaneswar & Cuttack",
    "state": "Odisha",
    "coordinates": [
      20.29,
      85.82
    ],
    "region": "ER",
    "peakDemandMw": 1150,
    "baseDemandMw": 980,
    "currentDemandMw": 980,
    "loadShedPct": 0,
    "voltageLevelKv": 132,
    "connectedSubstation": "Mendhasal 400/220kV Grid Substation",
    "discomOperator": "TPCODL / OPTCL",
    "operator": "TPCODL / OPTCL",
    "description": "Eastern technology education and healthcare hub powered by Talcher thermal and Balimela hydro generation feeds.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_2_COMMERCIAL"
  },
  {
    "id": "SNK-GUWAHATI",
    "name": "Guwahati Gateway of Northeast India",
    "category": "CITY_METRO",
    "city": "Guwahati / Kamrup Metropolitan",
    "state": "Assam",
    "coordinates": [
      26.14,
      91.73
    ],
    "region": "NER",
    "peakDemandMw": 580,
    "baseDemandMw": 490,
    "currentDemandMw": 490,
    "loadShedPct": 0,
    "voltageLevelKv": 132,
    "connectedSubstation": "Amingaon 220/132kV & Sarusajai Substation",
    "discomOperator": "APDCL",
    "operator": "APDCL",
    "description": "Primary commercial gateway to the seven Northeastern states interconnected with the national grid via the high-capacity chicken neck corridor.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_CRITICAL"
  },
  {
    "id": "SNK-KOCHI",
    "name": "Kochi Port & Industrial Belt",
    "category": "CITY_METRO",
    "city": "Kochi / Ernakulam",
    "state": "Kerala",
    "coordinates": [
      9.93,
      76.26
    ],
    "region": "SR",
    "peakDemandMw": 1420,
    "baseDemandMw": 1210,
    "currentDemandMw": 1210,
    "loadShedPct": 0,
    "voltageLevelKv": 110,
    "connectedSubstation": "Kalamassery 220/110kV & Brahmapuram",
    "discomOperator": "KSEB",
    "operator": "KSEB",
    "description": "Commercial capital of Kerala featuring international transshipment terminal Cochin Shipyard BPCL refinery and InfoPark.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_CRITICAL"
  },
  {
    "id": "SNK-INDORE",
    "name": "Indore Commercial & Auto Hub",
    "category": "CITY_METRO",
    "city": "Indore",
    "state": "Madhya Pradesh",
    "coordinates": [
      22.71,
      75.85
    ],
    "region": "WR",
    "peakDemandMw": 1350,
    "baseDemandMw": 1180,
    "currentDemandMw": 1180,
    "loadShedPct": 0,
    "voltageLevelKv": 132,
    "connectedSubstation": "Pithampur 400/220kV & Indore South Substation",
    "discomOperator": "MPPKVVCL",
    "operator": "MPPKVVCL",
    "description": "Commercial capital of MP and cleanest city in India with extensive commercial markets textile mills and electric city bus fleet.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_2_COMMERCIAL"
  },
  {
    "id": "SNK-CHANDIGARH",
    "name": "Chandigarh Tricity Urban Area",
    "category": "CITY_METRO",
    "city": "Chandigarh / Mohali / Panchkula",
    "state": "Chandigarh & Punjab",
    "coordinates": [
      30.73,
      76.77
    ],
    "region": "NR",
    "peakDemandMw": 950,
    "baseDemandMw": 810,
    "currentDemandMw": 810,
    "loadShedPct": 0,
    "voltageLevelKv": 66,
    "connectedSubstation": "Kishangarh 220/66kV Substation",
    "discomOperator": "Chandigarh Electricity Dept / PSPCL",
    "operator": "Chandigarh Electricity Dept / PSPCL",
    "description": "Planned administrative center of Punjab and Haryana with high per-capita electrical consumption and modern smart grid metering.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_2_COMMERCIAL"
  },
  {
    "id": "SNK-VADODARA",
    "name": "Vadodara Petrochemical & Engineering Hub",
    "category": "CITY_METRO",
    "city": "Vadodara",
    "state": "Gujarat",
    "coordinates": [
      22.3,
      73.18
    ],
    "region": "WR",
    "peakDemandMw": 1450,
    "baseDemandMw": 1260,
    "currentDemandMw": 1260,
    "loadShedPct": 0,
    "voltageLevelKv": 132,
    "connectedSubstation": "Koyali 220/66kV & Jambuva 220kV Substation",
    "discomOperator": "MGVCL / GETCO",
    "operator": "MGVCL / GETCO",
    "description": "Cultural and industrial hub hosting Gujarat Refinery heavy chemical complexes locomotive manufacturing and power transmission R&D.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_2_COMMERCIAL"
  },
  {
    "id": "SNK-HAZIRA",
    "name": "Hazira Petrochemical & Heavy Engineering Complex",
    "category": "FACTORY_HEAVY_INDUSTRY",
    "city": "Hazira / Surat",
    "state": "Gujarat",
    "coordinates": [
      21.11,
      72.67
    ],
    "region": "WR",
    "peakDemandMw": 1650,
    "baseDemandMw": 1420,
    "currentDemandMw": 1420,
    "loadShedPct": 0,
    "voltageLevelKv": 220,
    "connectedSubstation": "Mora 220kV & Hazira Gas Receiving Substation",
    "discomOperator": "GETCO",
    "operator": "GETCO",
    "description": "One of Asia's most power-dense coastal heavy industrial zones hosting Reliance Olefins AM/NS Steel and L&T Heavy Engineering.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_INDUSTRIAL"
  },
  {
    "id": "SNK-DAHEJ",
    "name": "Dahej Petroleum Chemicals & Petrochemicals Zone (PCPIR)",
    "category": "FACTORY_HEAVY_INDUSTRY",
    "city": "Dahej / Bharuch",
    "state": "Gujarat",
    "coordinates": [
      21.71,
      72.58
    ],
    "region": "WR",
    "peakDemandMw": 1200,
    "baseDemandMw": 1050,
    "currentDemandMw": 1050,
    "loadShedPct": 0,
    "voltageLevelKv": 220,
    "connectedSubstation": "Dahej 220/66kV Substation",
    "discomOperator": "GETCO Dahej Circle",
    "operator": "GETCO Dahej Circle",
    "description": "India's premier deep-water PCPIR chemical hub with energy-intensive electrolytic chlor-alkali plants ethylene crackers and LNG terminals.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_INDUSTRIAL"
  },
  {
    "id": "SNK-SANAND",
    "name": "Sanand Automobile & Semiconductor Mega Hub",
    "category": "FACTORY_HEAVY_INDUSTRY",
    "city": "Sanand GIDC / Ahmedabad",
    "state": "Gujarat",
    "coordinates": [
      23,
      72.38
    ],
    "region": "WR",
    "peakDemandMw": 580,
    "baseDemandMw": 480,
    "currentDemandMw": 480,
    "loadShedPct": 0,
    "voltageLevelKv": 66,
    "connectedSubstation": "Sanand GIDC-II 220/66kV Substation",
    "discomOperator": "UGVCL / GETCO",
    "operator": "UGVCL / GETCO",
    "description": "Automobile capital of western India and epicenter of India Semiconductor Mission hosting Micron ATMP and Tata Motors EV plant.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_INDUSTRIAL"
  },
  {
    "id": "SNK-SRIPERUMBUDUR",
    "name": "Sriperumbudur Electronics & Automotive Corridor",
    "category": "FACTORY_HEAVY_INDUSTRY",
    "city": "Sriperumbudur / Kanchipuram",
    "state": "Tamil Nadu",
    "coordinates": [
      12.98,
      79.94
    ],
    "region": "SR",
    "peakDemandMw": 780,
    "baseDemandMw": 690,
    "currentDemandMw": 690,
    "loadShedPct": 0,
    "voltageLevelKv": 110,
    "connectedSubstation": "Sriperumbudur 400/230/110kV Grid Substation",
    "discomOperator": "TANGEDCO",
    "operator": "TANGEDCO",
    "description": "Global electronics contract manufacturing hub and passenger car assembly belt hosting Foxconn iPhone campus and Hyundai Motor India.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_INDUSTRIAL"
  },
  {
    "id": "SNK-MORBI",
    "name": "Morbi Ceramic Tiles Industrial Cluster",
    "category": "FACTORY_HEAVY_INDUSTRY",
    "city": "Morbi",
    "state": "Gujarat",
    "coordinates": [
      22.82,
      70.83
    ],
    "region": "WR",
    "peakDemandMw": 820,
    "baseDemandMw": 720,
    "currentDemandMw": 720,
    "loadShedPct": 0,
    "voltageLevelKv": 66,
    "connectedSubstation": "Morbi-II 220/66kV Substation & Dhuva 66kV",
    "discomOperator": "PGVCL",
    "operator": "PGVCL",
    "description": "Second largest ceramic cluster in the world accounting for 90% of India's tile exports with continuous high-torque electric motor loads.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_2_COMMERCIAL"
  },
  {
    "id": "SNK-JAMSHEDPUR",
    "name": "Jamshedpur Steel & Heavy Engineering Works",
    "category": "FACTORY_HEAVY_INDUSTRY",
    "city": "Jamshedpur",
    "state": "Jharkhand",
    "coordinates": [
      22.8,
      86.2
    ],
    "region": "ER",
    "peakDemandMw": 950,
    "baseDemandMw": 860,
    "currentDemandMw": 860,
    "loadShedPct": 0,
    "voltageLevelKv": 132,
    "connectedSubstation": "Gamharia 220/132kV Substation & Tata Power Bus",
    "discomOperator": "Tata Power & JUSCO / DVC",
    "operator": "Tata Power & JUSCO / DVC",
    "description": "Pioneering industrial steel city of India with heavy electric arc furnaces blast furnace blowers and slab rolling mills.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_INDUSTRIAL"
  },
  {
    "id": "SNK-VISAKHAPATNAM-STEEL",
    "name": "Visakhapatnam Steel Plant (RINL) & Port PCPIR",
    "category": "FACTORY_HEAVY_INDUSTRY",
    "city": "Visakhapatnam",
    "state": "Andhra Pradesh",
    "coordinates": [
      17.68,
      83.21
    ],
    "region": "SR",
    "peakDemandMw": 1100,
    "baseDemandMw": 980,
    "currentDemandMw": 980,
    "loadShedPct": 0,
    "voltageLevelKv": 220,
    "connectedSubstation": "Kurmannapalem 220kV & Gajuwaka 400kV Substation",
    "discomOperator": "APEPDCL / APTRANSCO",
    "operator": "APEPDCL / APTRANSCO",
    "description": "Integrated shore-based steel plant (Vizag Steel) container port and petroleum refinery demanding round-the-clock uninterrupted power.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_INDUSTRIAL"
  },
  {
    "id": "SNK-BHILAI-STEEL",
    "name": "Bhilai Steel Plant (SAIL) & Rail Mill Complex",
    "category": "FACTORY_HEAVY_INDUSTRY",
    "city": "Bhilai / Durg District",
    "state": "Chhattisgarh",
    "coordinates": [
      21.19,
      81.38
    ],
    "region": "WR",
    "peakDemandMw": 1050,
    "baseDemandMw": 920,
    "currentDemandMw": 920,
    "loadShedPct": 0,
    "voltageLevelKv": 220,
    "connectedSubstation": "Bhilai 220kV & Rourkela Interconnect",
    "discomOperator": "CSPDCL / SAIL Dedicated Grid",
    "operator": "CSPDCL / SAIL Dedicated Grid",
    "description": "Sole producer of prestigious world-class long rails for Indian Railways with massive continuous blast furnace and caster electrical demand.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_INDUSTRIAL"
  },
  {
    "id": "SNK-ROURKELA-STEEL",
    "name": "Rourkela Steel Plant (SAIL) Heavy Complex",
    "category": "FACTORY_HEAVY_INDUSTRY",
    "city": "Rourkela / Sundargarh",
    "state": "Odisha",
    "coordinates": [
      22.22,
      84.85
    ],
    "region": "ER",
    "peakDemandMw": 980,
    "baseDemandMw": 860,
    "currentDemandMw": 860,
    "loadShedPct": 0,
    "voltageLevelKv": 220,
    "connectedSubstation": "Tarkera 220/132kV Substation",
    "discomOperator": "TPWODL / OPTCL",
    "operator": "TPWODL / OPTCL",
    "description": "First integrated steel plant in the public sector in India specialized in silicon steel for electrical transformers and defense grade plates.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_INDUSTRIAL"
  },
  {
    "id": "SNK-MANESAR-AUTO",
    "name": "Manesar - Gurugram Automobile Corridor",
    "category": "FACTORY_HEAVY_INDUSTRY",
    "city": "Manesar / IMT Gurugram",
    "state": "Haryana",
    "coordinates": [
      28.35,
      76.93
    ],
    "region": "NR",
    "peakDemandMw": 850,
    "baseDemandMw": 730,
    "currentDemandMw": 730,
    "loadShedPct": 0,
    "voltageLevelKv": 66,
    "connectedSubstation": "Manesar 220/66kV Substation",
    "discomOperator": "DHBVN",
    "operator": "DHBVN",
    "description": "Industrial Model Township hosting Maruti Suzuki integrated factory Honda Motorcycle and automotive supply chains.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_INDUSTRIAL"
  },
  {
    "id": "SNK-ANKLESHWAR",
    "name": "Ankleshwar - Panoli Chemical Industrial Estate",
    "category": "FACTORY_HEAVY_INDUSTRY",
    "city": "Ankleshwar / Bharuch",
    "state": "Gujarat",
    "coordinates": [
      21.62,
      73
    ],
    "region": "WR",
    "peakDemandMw": 620,
    "baseDemandMw": 540,
    "currentDemandMw": 540,
    "loadShedPct": 0,
    "voltageLevelKv": 66,
    "connectedSubstation": "Ankleshwar GIDC 66/11kV Substation",
    "discomOperator": "DGVCL / GETCO",
    "operator": "DGVCL / GETCO",
    "description": "One of the oldest and largest chemical industrial zones in Asia with over 1500 manufacturing units for pharmaceuticals dyes and agrochemicals.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_INDUSTRIAL"
  },
  {
    "id": "SNK-PITHAMPUR",
    "name": "Pithampur Special Economic Zone & Auto Belt",
    "category": "FACTORY_HEAVY_INDUSTRY",
    "city": "Pithampur / Dhar District",
    "state": "Madhya Pradesh",
    "coordinates": [
      22.61,
      75.68
    ],
    "region": "WR",
    "peakDemandMw": 540,
    "baseDemandMw": 460,
    "currentDemandMw": 460,
    "loadShedPct": 0,
    "voltageLevelKv": 66,
    "connectedSubstation": "Pithampur Sector-3 220/66kV Substation",
    "discomOperator": "MPPKVVCL",
    "operator": "MPPKVVCL",
    "description": "Known as the Detroit of Madhya Pradesh housing commercial vehicle manufacturing pharmaceutical formulation and engineering plants.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_INDUSTRIAL"
  },
  {
    "id": "SNK-DURGAPUR",
    "name": "Durgapur Steel City & Heavy Alloy Plant",
    "category": "FACTORY_HEAVY_INDUSTRY",
    "city": "Durgapur / Paschim Bardhaman",
    "state": "West Bengal",
    "coordinates": [
      23.52,
      87.31
    ],
    "region": "ER",
    "peakDemandMw": 720,
    "baseDemandMw": 620,
    "currentDemandMw": 620,
    "loadShedPct": 0,
    "voltageLevelKv": 132,
    "connectedSubstation": "Durgapur Projects Limited (DPL) Bus",
    "discomOperator": "DVC / WBSEDCL",
    "operator": "DVC / WBSEDCL",
    "description": "Heavy metallurgy and wheel-and-axle plant for Indian Railways locomotives operating heavy rolling mills on Damodar Valley grid.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_INDUSTRIAL"
  },
  {
    "id": "SNK-BALLABGARH",
    "name": "Ballabgarh - Faridabad Machinery Corridor",
    "category": "FACTORY_HEAVY_INDUSTRY",
    "city": "Faridabad / Ballabgarh",
    "state": "Haryana",
    "coordinates": [
      28.34,
      77.32
    ],
    "region": "NR",
    "peakDemandMw": 640,
    "baseDemandMw": 550,
    "currentDemandMw": 550,
    "loadShedPct": 0,
    "voltageLevelKv": 66,
    "connectedSubstation": "Sector 58 Faridabad 66kV Substation",
    "discomOperator": "DHBVN",
    "operator": "DHBVN",
    "description": "Heavy machinery engineering tractors electrical equipment and precision manufacturing hub on Delhi's southern industrial fringe.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_1_INDUSTRIAL"
  },
  {
    "id": "SNK-DWARKA-HOUSING",
    "name": "Dwarka Sub-City Residential Housing Complex",
    "category": "RESIDENTIAL_HOUSING",
    "city": "Dwarka / South-West Delhi",
    "state": "Delhi",
    "coordinates": [
      28.58,
      77.05
    ],
    "region": "NR",
    "peakDemandMw": 680,
    "baseDemandMw": 520,
    "currentDemandMw": 520,
    "loadShedPct": 0,
    "voltageLevelKv": 33,
    "connectedSubstation": "Dwarka Sector 8 & Sector 14 66/11kV Substations",
    "discomOperator": "BSES Rajdhani Power Limited (BRPL)",
    "operator": "BSES Rajdhani Power Limited (BRPL)",
    "description": "One of Asia's largest planned residential sub-cities with over 350 cooperative group housing societies smart rooftop solar and EV chargers.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_3_DOMESTIC"
  },
  {
    "id": "SNK-NAVI-MUMBAI-HOUSING",
    "name": "Navi Mumbai CIDCO Residential Townships",
    "category": "RESIDENTIAL_HOUSING",
    "city": "Vashi / Nerul / Kharghar / Panvel",
    "state": "Maharashtra",
    "coordinates": [
      19.03,
      73.02
    ],
    "region": "WR",
    "peakDemandMw": 540,
    "baseDemandMw": 420,
    "currentDemandMw": 420,
    "loadShedPct": 0,
    "voltageLevelKv": 22,
    "connectedSubstation": "Nerul 100/22kV & Kharghar 220/22kV Substation",
    "discomOperator": "MSEDCL",
    "operator": "MSEDCL",
    "description": "Planned residential satellite city nodes featuring high-rise cooperative apartment complexes suburban railway feeds and rooftop solar.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_3_DOMESTIC"
  },
  {
    "id": "SNK-WHITEFIELD-HOUSING",
    "name": "Whitefield Tech-Residential Apartment Corridor",
    "category": "RESIDENTIAL_HOUSING",
    "city": "Whitefield / Kadugodi / Hoodi",
    "state": "Karnataka",
    "coordinates": [
      12.96,
      77.75
    ],
    "region": "SR",
    "peakDemandMw": 480,
    "baseDemandMw": 380,
    "currentDemandMw": 380,
    "loadShedPct": 0,
    "voltageLevelKv": 11,
    "connectedSubstation": "Hoodi 66/11kV Distribution Substation",
    "discomOperator": "BESCOM",
    "operator": "BESCOM",
    "description": "Dense high-rise apartment townships housing IT and engineering professionals with automated time-of-day metering and distributed solar.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_3_DOMESTIC"
  },
  {
    "id": "SNK-BOPAL-HOUSING",
    "name": "Bopal - South Bopal - Gota Residential Housing Belt",
    "category": "RESIDENTIAL_HOUSING",
    "city": "Ahmedabad Western Suburbs",
    "state": "Gujarat",
    "coordinates": [
      23.03,
      72.46
    ],
    "region": "WR",
    "peakDemandMw": 360,
    "baseDemandMw": 280,
    "currentDemandMw": 280,
    "loadShedPct": 0,
    "voltageLevelKv": 11,
    "connectedSubstation": "Bopal 66/11kV Substation & Ghuma",
    "discomOperator": "Torrent Power Limited",
    "operator": "Torrent Power Limited",
    "description": "Rapidly expanding western Ahmedabad residential high-rise belt with highest rooftop solar penetration per square kilometer in western India.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_3_DOMESTIC"
  },
  {
    "id": "SNK-NOIDA-EXPRESSWAY",
    "name": "Noida Expressway High-Rise Townships",
    "category": "RESIDENTIAL_HOUSING",
    "city": "Noida Sectors 128-168 / Greater Noida",
    "state": "Uttar Pradesh",
    "coordinates": [
      28.53,
      77.39
    ],
    "region": "NR",
    "peakDemandMw": 590,
    "baseDemandMw": 480,
    "currentDemandMw": 480,
    "loadShedPct": 0,
    "voltageLevelKv": 33,
    "connectedSubstation": "Noida Sector 148 400/220/33kV Substation",
    "discomOperator": "NPCL / PVVNL",
    "operator": "NPCL / PVVNL",
    "description": "Modern high-rise residential towers and integrated township developments with continuous air conditioning demand and smart prepayment meters.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_3_DOMESTIC"
  },
  {
    "id": "SNK-HINJEWADI-HOUSING",
    "name": "Hinjewadi Infotech Residential Townships",
    "category": "RESIDENTIAL_HOUSING",
    "city": "Hinjewadi / Wakad / Baner",
    "state": "Maharashtra",
    "coordinates": [
      18.59,
      73.71
    ],
    "region": "WR",
    "peakDemandMw": 510,
    "baseDemandMw": 410,
    "currentDemandMw": 410,
    "loadShedPct": 0,
    "voltageLevelKv": 22,
    "connectedSubstation": "Hinjewadi 220/22kV Substation",
    "discomOperator": "MSEDCL",
    "operator": "MSEDCL",
    "description": "High-density IT professional residential corridor adjacent to Rajiv Gandhi Infotech Park with high smart meter EV adoption.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_3_DOMESTIC"
  },
  {
    "id": "SNK-MADHAPUR-HOUSING",
    "name": "Madhapur - Gachibowli Cyber High-Rise Corridor",
    "category": "RESIDENTIAL_HOUSING",
    "city": "HITEC City / Kondapur / Financial District",
    "state": "Telangana",
    "coordinates": [
      17.44,
      78.38
    ],
    "region": "SR",
    "peakDemandMw": 580,
    "baseDemandMw": 470,
    "currentDemandMw": 470,
    "loadShedPct": 0,
    "voltageLevelKv": 33,
    "connectedSubstation": "Madhapur 220/33kV Substation",
    "discomOperator": "TSSPDCL",
    "operator": "TSSPDCL",
    "description": "Premium residential towers and gated communities housing Hyderabad's technology workforce with advanced smart grid distribution.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_3_DOMESTIC"
  },
  {
    "id": "SNK-NEW-TOWN-KOLKATA",
    "name": "New Town Rajarhat Smart City & Townships",
    "category": "RESIDENTIAL_HOUSING",
    "city": "New Town / Rajarhat / Action Area I-III",
    "state": "West Bengal",
    "coordinates": [
      22.58,
      88.47
    ],
    "region": "ER",
    "peakDemandMw": 440,
    "baseDemandMw": 350,
    "currentDemandMw": 350,
    "loadShedPct": 0,
    "voltageLevelKv": 33,
    "connectedSubstation": "New Town 220/33kV GIS Substation",
    "discomOperator": "WBSEDCL",
    "operator": "WBSEDCL",
    "description": "Planned green smart city township featuring automated solar street lighting electric vehicle fleet chargers and residential complexes.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_3_DOMESTIC"
  },
  {
    "id": "SNK-DMRC-TRACTION",
    "name": "Delhi Metro Rail Corporation (DMRC) Electric Traction",
    "category": "TRANSIT_CRITICAL_INFRA",
    "city": "Delhi-NCR Metro Network",
    "state": "Delhi",
    "coordinates": [
      28.63,
      77.21
    ],
    "region": "NR",
    "peakDemandMw": 320,
    "baseDemandMw": 260,
    "currentDemandMw": 260,
    "loadShedPct": 0,
    "voltageLevelKv": 25,
    "connectedSubstation": "Kashmere Gate 66/25kV & Yamuna Bank Substations",
    "discomOperator": "DMRC Traction / DTL",
    "operator": "DMRC Traction / DTL",
    "description": "Vital public transit lifeline ferrying 6 million daily passengers across NCR. Exempt from all ordinary load-shedding with dual redundant supply.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_0_LIFELINE"
  },
  {
    "id": "SNK-MUMBAI-DATA-CENTERS",
    "name": "Navi Mumbai Airoli - Mahape Data Center Campus",
    "category": "TRANSIT_CRITICAL_INFRA",
    "city": "Airoli / Mahape / TTC Industrial Area",
    "state": "Maharashtra",
    "coordinates": [
      19.16,
      73
    ],
    "region": "WR",
    "peakDemandMw": 420,
    "baseDemandMw": 390,
    "currentDemandMw": 390,
    "loadShedPct": 0,
    "voltageLevelKv": 100,
    "connectedSubstation": "Airoli 220/100kV Substation & Kalwa Loop",
    "discomOperator": "MSEDCL Dedicated Express Feeders",
    "operator": "MSEDCL Dedicated Express Feeders",
    "description": "Largest cloud and AI hyperscale data center cluster in India with 24/7 flat baseload demand dual 100 kV grid feeds and BESS storage.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_0_LIFELINE"
  },
  {
    "id": "SNK-JNPT-PORT",
    "name": "Jawaharlal Nehru Port Trust (JNPT) & Nhava Sheva",
    "category": "TRANSIT_CRITICAL_INFRA",
    "city": "Nhava Sheva / Navi Mumbai",
    "state": "Maharashtra",
    "coordinates": [
      18.95,
      72.95
    ],
    "region": "WR",
    "peakDemandMw": 280,
    "baseDemandMw": 240,
    "currentDemandMw": 240,
    "loadShedPct": 0,
    "voltageLevelKv": 33,
    "connectedSubstation": "JNPT 110/33kV Dedicated Substation",
    "discomOperator": "MSEDCL / Port Authority",
    "operator": "MSEDCL / Port Authority",
    "description": "India's premier container transshipment port handling over 50% of the nation's containerized cargo with electric quay cranes and cold ironing.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_0_LIFELINE"
  },
  {
    "id": "SNK-WESTERN-DFC",
    "name": "Western Dedicated Freight Corridor (WDFC) Electric Traction",
    "category": "TRANSIT_CRITICAL_INFRA",
    "city": "WDFC Railway Corridor (Dadri to JNPT)",
    "state": "Rajasthan & Gujarat",
    "coordinates": [
      24.58,
      73.71
    ],
    "region": "WR",
    "peakDemandMw": 450,
    "baseDemandMw": 380,
    "currentDemandMw": 380,
    "loadShedPct": 0,
    "voltageLevelKv": 25,
    "connectedSubstation": "Dedicated 132/25kV Traction Power Substations",
    "discomOperator": "DFCCIL / Ministry of Railways",
    "operator": "DFCCIL / Ministry of Railways",
    "description": "High-speed freight railway corridor linking northern industrial hinterland to western ports powered by high-efficiency 2x25kV AC traction.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_0_LIFELINE"
  },
  {
    "id": "SNK-CHENNAI-DC",
    "name": "Chennai Ambattur Hyperscale Data Center Park",
    "category": "TRANSIT_CRITICAL_INFRA",
    "city": "Ambattur Industrial Estate / Siruseri",
    "state": "Tamil Nadu",
    "coordinates": [
      13.11,
      80.15
    ],
    "region": "SR",
    "peakDemandMw": 380,
    "baseDemandMw": 350,
    "currentDemandMw": 350,
    "loadShedPct": 0,
    "voltageLevelKv": 110,
    "connectedSubstation": "Ambattur 230/110kV GIS Substation",
    "discomOperator": "TANGEDCO",
    "operator": "TANGEDCO",
    "description": "Critical coastal data center hub hosting international undersea fiber landings and ultra-high-density enterprise cloud infrastructure.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_0_LIFELINE"
  },
  {
    "id": "SNK-BMRCL-METRO",
    "name": "Namma Metro (Bengaluru Metro) Electric Traction",
    "category": "TRANSIT_CRITICAL_INFRA",
    "city": "Bengaluru Metro Lines",
    "state": "Karnataka",
    "coordinates": [
      12.97,
      77.56
    ],
    "region": "SR",
    "peakDemandMw": 190,
    "baseDemandMw": 150,
    "currentDemandMw": 150,
    "loadShedPct": 0,
    "voltageLevelKv": 33,
    "connectedSubstation": "Peenya & Baiyappanahalli 66/33kV Traction Substations",
    "discomOperator": "BESCOM / BMRCL",
    "operator": "BESCOM / BMRCL",
    "description": "Rapid transit rail network serving Bengaluru commuters with regenerative braking feeds returning power back into the local 33kV grid.",
    "status": "NORMAL",
    "drActive": false,
    "priorityLevel": "TIER_0_LIFELINE"
  }
];
