// Real-World Indian Electricity Demand Sinks: Cities, Heavy Industrial Factories, Residential Housing & Critical Infrastructure
// Sourced from DISCOM Load Curves, CEA Power Supply Position Reports, State GIDC & Urban Development Authorities.

export const ELECTRICITY_SINKS = [
  // =========================================================================
  // 1. CITIES & METROPOLITAN DEMAND SINKS
  // =========================================================================
  {
    id: "SNK-DELHI",
    name: "Delhi-NCR Megacity & Commercial Hub",
    category: "CITY_METRO",
    city: "National Capital Region (Delhi / Noida / Gurugram)",
    state: "Delhi & NCR",
    coordinates: [28.61, 77.23],
    region: "NR",
    peakDemandMw: 8656,
    baseDemandMw: 7420,
    currentDemandMw: 7420,
    loadShedPct: 0,
    voltageLevelKv: 66,
    consumerBreakdown: {
      domesticResidentialPct: 48,
      commercialOfficesPct: 32,
      industrialPct: 12,
      publicTransitAndServicesPct: 8
    },
    totalMeteredConsumers: 6850000,
    connectedSubstation: "Mayur Vihar 66/11kV Substation & Bawana 400kV",
    discomOperator: "BSES Yamuna / BSES Rajdhani / TPDDL / DTL",
    description: "Highest peak load density in Northern Grid. Record peak demand exceeding 8,656 MW during summer heatwaves with extreme air-conditioning load swings.",
    status: "NORMAL",
    drActive: false,
    priorityLevel: "TIER_1_CRITICAL"
  },
  {
    id: "SNK-MUMBAI",
    name: "Mumbai Metropolitan Region (MMR)",
    category: "CITY_METRO",
    city: "Mumbai / Thane / Navi Mumbai",
    state: "Maharashtra",
    coordinates: [19.07, 72.87],
    region: "WR",
    peakDemandMw: 4300,
    baseDemandMw: 3850,
    currentDemandMw: 3850,
    loadShedPct: 0,
    voltageLevelKv: 220,
    consumerBreakdown: {
      commercialFinancialPct: 42,
      domesticResidentialPct: 38,
      industrialThaneBelapurPct: 15,
      suburbanRailwayTractionPct: 5
    },
    totalMeteredConsumers: 4200000,
    connectedSubstation: "Kalwa 400/220kV Receiving Station & Trombay",
    discomOperator: "Adani Electricity Mumbai / Tata Power / BEST / MSEDCL",
    description: "Financial capital hub supplied by Western Grid transmission lines and protected by an automated islanding scheme preventing blackout cascades.",
    status: "NORMAL",
    drActive: false,
    priorityLevel: "TIER_1_CRITICAL"
  },
  {
    id: "SNK-BLR",
    name: "Bengaluru Tech & Electronics City Belt",
    category: "CITY_METRO",
    city: "Bengaluru Urban",
    state: "Karnataka",
    coordinates: [12.97, 77.59],
    region: "SR",
    peakDemandMw: 3450,
    baseDemandMw: 3120,
    currentDemandMw: 3120,
    loadShedPct: 0,
    voltageLevelKv: 220,
    consumerBreakdown: {
      itParksAndDataCentersPct: 35,
      domesticResidentialPct: 40,
      precisionManufacturingPct: 18,
      metroAndServicesPct: 7
    },
    totalMeteredConsumers: 3900000,
    connectedSubstation: "Hoodi 400/220kV Substation & Nelamangala",
    discomOperator: "BESCOM (Bangalore Electricity Supply Company)",
    description: "High-density technology corridor powering Electronic City, Whitefield tech campuses, semiconductor R&D, and aerospace engineering clusters.",
    status: "NORMAL",
    drActive: false,
    priorityLevel: "TIER_1_CRITICAL"
  },
  {
    id: "SNK-AHMEDABAD",
    name: "Ahmedabad Urban Area",
    category: "CITY_METRO",
    city: "Ahmedabad & Gandhinagar",
    state: "Gujarat",
    coordinates: [23.02, 72.57],
    region: "WR",
    peakDemandMw: 2800,
    baseDemandMw: 2480,
    currentDemandMw: 2480,
    loadShedPct: 0,
    voltageLevelKv: 132,
    consumerBreakdown: {
      domesticResidentialPct: 45,
      commercialAndGIFTpct: 28,
      industrialEstatesPct: 22,
      metroTransitPct: 5
    },
    totalMeteredConsumers: 2400000,
    connectedSubstation: "Pirana 400kV Substation & Sabarmati",
    discomOperator: "Torrent Power Limited / UGVCL",
    description: "Commercial and administrative core of Gujarat including GIFT City International Financial Services Centre, Sabarmati high-voltage grid loop.",
    status: "NORMAL",
    drActive: false,
    priorityLevel: "TIER_1_CRITICAL"
  },
  {
    id: "SNK-SURAT",
    name: "Surat Textile & Diamond City",
    category: "CITY_METRO",
    city: "Surat",
    state: "Gujarat",
    coordinates: [21.17, 72.83],
    region: "WR",
    peakDemandMw: 2100,
    baseDemandMw: 1850,
    currentDemandMw: 1850,
    loadShedPct: 0,
    voltageLevelKv: 66,
    consumerBreakdown: {
      textilePowerloomsPct: 40,
      diamondCuttingBoursePct: 25,
      residentialUrbanPct: 30,
      servicesPct: 5
    },
    totalMeteredConsumers: 1750000,
    connectedSubstation: "Ichhapore 220kV & Surat City Gas Turbine Receiving Station",
    discomOperator: "Torrent Power Limited / DGVCL",
    description: "Global diamond polishing and synthetic textile manufacturing epicenter. Powered directly by Ukai Hydro, Kakrapar Nuclear, and Hazira thermal corridors.",
    status: "NORMAL",
    drActive: false,
    priorityLevel: "TIER_2_COMMERCIAL"
  },
  {
    id: "SNK-CHENNAI",
    name: "Chennai Metropolitan Area",
    category: "CITY_METRO",
    city: "Chennai & Suburbs",
    state: "Tamil Nadu",
    coordinates: [13.08, 80.27],
    region: "SR",
    peakDemandMw: 3900,
    baseDemandMw: 3510,
    currentDemandMw: 3510,
    loadShedPct: 0,
    voltageLevelKv: 230,
    consumerBreakdown: {
      domesticResidentialPct: 44,
      itAndHealthcarePct: 26,
      portsAndAutomotivePct: 24,
      metroAndRailPct: 6
    },
    totalMeteredConsumers: 3400000,
    connectedSubstation: "Sriperumbudur 400kV Substation & Alamathy",
    discomOperator: "TANGEDCO",
    description: "Southern manufacturing hub, automotive Detroit of India, hyperscale submarine cable landing data centers, and major container ports.",
    status: "NORMAL",
    drActive: false,
    priorityLevel: "TIER_1_CRITICAL"
  },
  {
    id: "SNK-KOLKATA",
    name: "Kolkata - Howrah Metropolitan Belt",
    category: "CITY_METRO",
    city: "Kolkata & Howrah",
    state: "West Bengal",
    coordinates: [22.57, 88.36],
    region: "ER",
    peakDemandMw: 2600,
    baseDemandMw: 2250,
    currentDemandMw: 2250,
    loadShedPct: 0,
    voltageLevelKv: 132,
    consumerBreakdown: {
      domesticUrbanPct: 50,
      commercialOfficesPct: 25,
      foundryAndJuteMillsPct: 18,
      metroAndTractionPct: 7
    },
    totalMeteredConsumers: 3100000,
    connectedSubstation: "Subhashgram 400kV Substation & Titagarh",
    discomOperator: "CESC Limited / WBSEDCL",
    description: "Historic cultural and trade center of Eastern India with intensive underground electric grid network and East-West Metro underwater tunnel lines.",
    status: "NORMAL",
    drActive: false,
    priorityLevel: "TIER_1_CRITICAL"
  },

  // =========================================================================
  // 2. FACTORIES & HEAVY INDUSTRIAL CLUSTERS (MEGAWATT-SCALE SINKS)
  // =========================================================================
  {
    id: "SNK-HAZIRA",
    name: "Hazira Petrochemical & Heavy Engineering Complex",
    category: "FACTORY_HEAVY_INDUSTRY",
    city: "Hazira / Surat",
    state: "Gujarat",
    coordinates: [21.11, 72.67],
    region: "WR",
    peakDemandMw: 1650,
    baseDemandMw: 1420,
    currentDemandMw: 1420,
    loadShedPct: 0,
    voltageLevelKv: 220,
    anchorIndustries: [
      "Reliance Industries Hazira (Olefins, Polymers, Monoethylene Glycol)",
      "ArcelorMittal Nippon Steel (AM/NS) 9 MTPA Integrated Steel Complex",
      "Larsen & Toubro (L&T) Heavy Engineering & Defense Submarine Fabrication",
      "Shell Hazira LNG Regasification Terminal",
      "KRIBHCO Fertilizer Plant"
    ],
    connectedSubstation: "Mora 220kV & Hazira Gas Receiving Substation",
    operator: "Gujarat Energy Transmission Corporation (GETCO)",
    description: "One of Asia's most power-dense coastal heavy industrial zones. Requires continuous uninterrupted 220 kV feed from Kakrapar Nuclear, Ukai Dam, and gas turbines.",
    status: "NORMAL",
    drActive: false,
    priorityLevel: "TIER_1_INDUSTRIAL"
  },
  {
    id: "SNK-DAHEJ",
    name: "Dahej Petroleum, Chemicals & Petrochemicals Zone (PCPIR)",
    category: "FACTORY_HEAVY_INDUSTRY",
    city: "Dahej / Bharuch",
    state: "Gujarat",
    coordinates: [21.71, 72.58],
    region: "WR",
    peakDemandMw: 1200,
    baseDemandMw: 1050,
    currentDemandMw: 1050,
    loadShedPct: 0,
    voltageLevelKv: 220,
    anchorIndustries: [
      "ONGC Petro additions Limited (OPaL) Mega Dual Feed Cracker Complex",
      "Petronet LNG Terminal",
      "GACL Caustic Soda Chlor-Alkali Complex",
      "Birla Copper (Hindalco Smelter)",
      "Rallis & Meghmani Chemical Manufacturing"
    ],
    connectedSubstation: "Dahej 220/66kV Substation",
    operator: "GETCO Dahej Transmission Circle",
    description: "India's premier deep-water PCPIR chemical hub with energy-intensive electrolytic chlor-alkali plants, ethylene crackers, and LNG facilities.",
    status: "NORMAL",
    drActive: false,
    priorityLevel: "TIER_1_INDUSTRIAL"
  },
  {
    id: "SNK-SANAND",
    name: "Sanand Automobile & Semiconductor Mega Hub",
    category: "FACTORY_HEAVY_INDUSTRY",
    city: "Sanand GIDC / Ahmedabad",
    state: "Gujarat",
    coordinates: [23.00, 72.38],
    region: "WR",
    peakDemandMw: 580,
    baseDemandMw: 480,
    currentDemandMw: 480,
    loadShedPct: 0,
    voltageLevelKv: 66,
    anchorIndustries: [
      "Tata Motors Passenger & EV Manufacturing Plant (Nexon EV / Tiago EV)",
      "Micron Technology Semiconductor Assembly, Test & Packaging (ATMP)",
      "Ford India Transmission Plant",
      "Colgate-Palmolive & Bosch Tier-1 Auto Components"
    ],
    connectedSubstation: "Sanand GIDC-II 220/66kV Substation",
    operator: "UGVCL / GETCO",
    description: "Automobile capital of western India and epicenter of India Semiconductor Mission. Highly sensitive to voltage sags and sub-cycle micro-interruptions.",
    status: "NORMAL",
    drActive: false,
    priorityLevel: "TIER_1_INDUSTRIAL"
  },
  {
    id: "SNK-SRIPERUMBUDUR",
    name: "Sriperumbudur Electronics & Automotive Corridor",
    category: "FACTORY_HEAVY_INDUSTRY",
    city: "Sriperumbudur / Kanchipuram",
    state: "Tamil Nadu",
    coordinates: [12.98, 79.94],
    region: "SR",
    peakDemandMw: 780,
    baseDemandMw: 690,
    currentDemandMw: 690,
    loadShedPct: 0,
    voltageLevelKv: 110,
    anchorIndustries: [
      "Foxconn Hon Hai iPhone Assembly Mega Campus",
      "Hyundai Motor India Integrated Assembly Plant",
      "Samsung Electronics Air-Conditioner & Refrigerator Plant",
      "Saint-Gobain World Glass Complex"
    ],
    connectedSubstation: "Sriperumbudur 400/230/110kV Grid Substation",
    operator: "TANGEDCO",
    description: "Global electronics contract manufacturing hub and passenger car assembly belt directly connected to Sriperumbudur 400kV inter-regional substation.",
    status: "NORMAL",
    drActive: false,
    priorityLevel: "TIER_1_INDUSTRIAL"
  },
  {
    id: "SNK-MORBI",
    name: "Morbi Ceramic Tiles Industrial Cluster",
    category: "FACTORY_HEAVY_INDUSTRY",
    city: "Morbi",
    state: "Gujarat",
    coordinates: [22.82, 70.83],
    region: "WR",
    peakDemandMw: 820,
    baseDemandMw: 720,
    currentDemandMw: 720,
    loadShedPct: 0,
    voltageLevelKv: 66,
    anchorIndustries: [
      "Over 850 Continuous Roller Kiln Ceramic & Porcelain Tile Factories",
      "Kajaria, Somany, Asian Granito & Simpolo Production Units",
      "Heavy Sanitaryware Slip-Casting Facilities"
    ],
    connectedSubstation: "Morbi-II 220/66kV Substation & Dhuva 66kV",
    operator: "PGVCL (Paschim Gujarat Vij Company)",
    description: "Second largest ceramic cluster in the world (accounting for 90% of India's tile exports). High continuous electrical motor and automated kiln loading baseload.",
    status: "NORMAL",
    drActive: false,
    priorityLevel: "TIER_2_COMMERCIAL"
  },
  {
    id: "SNK-JAMSHEDPUR",
    name: "Jamshedpur Steel & Heavy Engineering Works",
    category: "FACTORY_HEAVY_INDUSTRY",
    city: "Jamshedpur",
    state: "Jharkhand",
    coordinates: [22.80, 86.20],
    region: "ER",
    peakDemandMw: 950,
    baseDemandMw: 860,
    currentDemandMw: 860,
    loadShedPct: 0,
    voltageLevelKv: 132,
    anchorIndustries: [
      "Tata Steel Jamshedpur 11 MTPA Integrated Blast Furnaces & Rolling Mills",
      "Tata Motors Heavy Commercial Vehicles Assembly",
      "Tata Power Jojobera Thermal & DVC Interconnect"
    ],
    connectedSubstation: "Gamharia 220/132kV Substation & Tata Power Bus",
    operator: "Tata Power & JUSCO / DVC",
    description: "Pioneering industrial steel city of India. Heavy electric arc furnaces, blast furnace blowers, and slab rolling mills requiring immense reactive power support.",
    status: "NORMAL",
    drActive: false,
    priorityLevel: "TIER_1_INDUSTRIAL"
  },

  // =========================================================================
  // 3. HOUSES & RESIDENTIAL TOWNSHIPS (HIGH-DENSITY DOMESTIC SINKS)
  // =========================================================================
  {
    id: "SNK-DWARKA-HOUSING",
    name: "Dwarka Sub-City Residential Housing Complex",
    category: "RESIDENTIAL_HOUSING",
    city: "Dwarka / South-West Delhi",
    state: "Delhi",
    coordinates: [28.58, 77.05],
    region: "NR",
    peakDemandMw: 680,
    baseDemandMw: 520,
    currentDemandMw: 520,
    loadShedPct: 0,
    voltageLevelKv: 33,
    housingProfile: {
      residentialSocietiesCount: 350,
      totalHousingApartments: 280000,
      estimatedResidents: 1250000,
      evChargersInstalled: 1800,
      rooftopSolarMw: 14.5
    },
    connectedSubstation: "Dwarka Sector 8 & Sector 14 66/11kV Grid Substations",
    discomOperator: "BSES Rajdhani Power Limited (BRPL)",
    description: "One of Asia's largest planned residential sub-cities with over 350 cooperative group housing societies, smart rooftop solar meters, and EV charging points.",
    status: "NORMAL",
    drActive: false,
    priorityLevel: "TIER_3_DOMESTIC"
  },
  {
    id: "SNK-NAVI-MUMBAI-HOUSING",
    name: "Navi Mumbai CIDCO Residential Townships",
    category: "RESIDENTIAL_HOUSING",
    city: "Vashi / Nerul / Kharghar / Panvel",
    state: "Maharashtra",
    coordinates: [19.03, 73.02],
    region: "WR",
    peakDemandMw: 540,
    baseDemandMw: 420,
    currentDemandMw: 420,
    loadShedPct: 0,
    voltageLevelKv: 22,
    housingProfile: {
      totalHousingApartments: 320000,
      estimatedResidents: 1400000,
      rooftopSolarMw: 18.2
    },
    connectedSubstation: "Nerul 100/22kV & Kharghar 220/22kV Substation",
    discomOperator: "MSEDCL (Maharashtra State Electricity Distribution)",
    description: "Planned residential satellite city nodes featuring high-rise cooperative apartment complexes, suburban railway feeder stations, and domestic distribution transformers.",
    status: "NORMAL",
    drActive: false,
    priorityLevel: "TIER_3_DOMESTIC"
  },
  {
    id: "SNK-WHITEFIELD-HOUSING",
    name: "Whitefield Tech-Residential Apartment Corridor",
    category: "RESIDENTIAL_HOUSING",
    city: "Whitefield / Kadugodi / Hoodi",
    state: "Karnataka",
    coordinates: [12.96, 77.75],
    region: "SR",
    peakDemandMw: 480,
    baseDemandMw: 380,
    currentDemandMw: 380,
    loadShedPct: 0,
    voltageLevelKv: 11,
    housingProfile: {
      residentialHighRiseTowers: 140,
      totalHousingApartments: 195000,
      estimatedResidents: 850000,
      smartMetersInstalled: "100% AMI",
      rooftopSolarMw: 22.0
    },
    connectedSubstation: "Hoodi 66/11kV Distribution Substation",
    discomOperator: "BESCOM",
    description: "Dense high-rise apartment townships housing IT and engineering professionals, with automated time-of-day (ToD) metering and distributed solar feed-in.",
    status: "NORMAL",
    drActive: false,
    priorityLevel: "TIER_3_DOMESTIC"
  },
  {
    id: "SNK-BOPAL-HOUSING",
    name: "Bopal - South Bopal - Gota Residential Housing Belt",
    category: "RESIDENTIAL_HOUSING",
    city: "Ahmedabad Western Suburbs",
    state: "Gujarat",
    coordinates: [23.03, 72.46],
    region: "WR",
    peakDemandMw: 360,
    baseDemandMw: 280,
    currentDemandMw: 280,
    loadShedPct: 0,
    voltageLevelKv: 11,
    housingProfile: {
      residentialHighRiseTowers: 110,
      totalHousingApartments: 145000,
      estimatedResidents: 620000,
      rooftopSolarMw: 35.0
    },
    connectedSubstation: "Bopal 66/11kV Substation & Ghuma",
    discomOperator: "Torrent Power Limited",
    description: "Rapidly expanding western Ahmedabad residential high-rise belt with highest rooftop solar penetration per square kilometer in western India.",
    status: "NORMAL",
    drActive: false,
    priorityLevel: "TIER_3_DOMESTIC"
  },

  // =========================================================================
  // 4. TRANSIT & CRITICAL INFRASTRUCTURE SINKS
  // =========================================================================
  {
    id: "SNK-DMRC-TRACTION",
    name: "Delhi Metro Rail Corporation (DMRC) Electric Traction",
    category: "TRANSIT_CRITICAL_INFRA",
    city: "Delhi-NCR Metro Network",
    state: "Delhi",
    coordinates: [28.63, 77.21],
    region: "NR",
    peakDemandMw: 320,
    baseDemandMw: 260,
    currentDemandMw: 260,
    loadShedPct: 0,
    voltageLevelKv: 25,
    tractionSpecs: {
      trackRouteKm: 393,
      trainSetsRunning: 340,
      overheadLineVoltageKv: "25 kV AC Single Phase Catenary",
      regenerativeBrakingEnergyReturnedPct: 32
    },
    connectedSubstation: "Kashmere Gate 66/25kV & Yamuna Bank Traction Substations",
    discomOperator: "DMRC Dedicated Traction Feeder / DTL",
    description: "Vital public transit lifeline ferrying 6 million daily passengers across NCR. Exempt from all ordinary load-shedding protocols with dual redundant supply.",
    status: "NORMAL",
    drActive: false,
    priorityLevel: "TIER_0_LIFELINE"
  },
  {
    id: "SNK-MUMBAI-DATA-CENTERS",
    name: "Navi Mumbai Airoli - Mahape Hyperscale Data Center Campus",
    category: "TRANSIT_CRITICAL_INFRA",
    city: "Airoli / Mahape / TTC Industrial Area",
    state: "Maharashtra",
    coordinates: [19.16, 73.00],
    region: "WR",
    peakDemandMw: 420,
    baseDemandMw: 390,
    currentDemandMw: 390,
    loadShedPct: 0,
    voltageLevelKv: 100,
    dcSpecs: {
      serverRacksCount: "45,000+ High-Density GPU Racks",
      uptimeTier: "Tier IV Fault Tolerant (99.995% Uptime)",
      operators: ["CtrlS", "NTT Global", "STT GDC", "AdaniConneX", "Equinix"]
    },
    connectedSubstation: "Airoli 220/100kV Substation & Kalwa Loop",
    discomOperator: "MSEDCL Dedicated Express Feeders",
    description: "Largest cloud and AI data center cluster in India. 24/7 flat baseload demand with dual 100 kV incoming grid feeds and on-site BESS energy storage.",
    status: "NORMAL",
    drActive: false,
    priorityLevel: "TIER_0_LIFELINE"
  }
];

export const SINK_CATEGORY_METRICS = {
  CITY_METRO: { color: "#10b981", icon: "🏙️", label: "City & Metropolitan Hub" },
  FACTORY_HEAVY_INDUSTRY: { color: "#f59e0b", icon: "🏭", label: "Factory & Heavy Industry" },
  RESIDENTIAL_HOUSING: { color: "#38bdf8", icon: "🏘️", label: "Houses & Townships" },
  TRANSIT_CRITICAL_INFRA: { color: "#ef4444", icon: "🚆", label: "Transit & Critical Infrastructure" }
};
