// Real-World Indian Electricity Sources: Hydro Dams, Nuclear, Solar Parks, Wind Complexes & Thermal Plants
// Sourced from Central Electricity Authority (CEA), Grid-India (POSOCO), NPCIL, NHPC, GUVNL & State Gencos.

export const ELECTRICITY_SOURCES = [
  {
    "id": "SRC-UKAI",
    "name": "Ukai Dam Hydro Power Plant (Vallabh Sagar)",
    "location": "Songadh / Tapi District",
    "state": "Gujarat",
    "riverBasin": "Tapi River",
    "coordinates": [
      21.25,
      73.58
    ],
    "region": "WR",
    "type": "HYDRO_DAM",
    "subtype": "Storage Reservoir Hydro",
    "capacityMw": 300,
    "currentGenMw": 240,
    "minDispatchMw": 50,
    "maxDispatchMw": 300,
    "voltageKv": 220,
    "unitsCount": 4,
    "unitDetails": "4 x 75 MW Francis Turbines (BHEL)",
    "fuelType": "Hydro",
    "operator": "Gujarat State Electricity Corporation Limited (GSECL)",
    "description": "Multipurpose earth-cum-masonry dam on Tapi river. Provides rapid peaking power irrigation and flood mitigation to Surat downstream.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-SURAT"
  },
  {
    "id": "SRC-SARDAR-SAROVAR",
    "name": "Sardar Sarovar Dam Hydro Project (Narmada Hydro)",
    "location": "Kevadia / Narmada District",
    "state": "Gujarat",
    "riverBasin": "Narmada River",
    "coordinates": [
      21.83,
      73.75
    ],
    "region": "WR",
    "type": "HYDRO_DAM",
    "subtype": "Underground RBPH & Canal Head Station",
    "capacityMw": 1450,
    "currentGenMw": 1180,
    "minDispatchMw": 250,
    "maxDispatchMw": 1450,
    "voltageKv": 400,
    "unitsCount": 11,
    "unitDetails": "6 x 200 MW RBPH Francis Turbines + 5 x 50 MW CHPH Kaplan Turbines",
    "fuelType": "Hydro",
    "operator": "Sardar Sarovar Narmada Nigam Ltd (SSNNL) / NCA",
    "description": "Monumental gravity dam on Narmada River with 1200 MW underground pumped-storage capable river bed power station. Shared between Gujarat MP and Maharashtra.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-AHMEDABAD"
  },
  {
    "id": "SRC-TEHRI",
    "name": "Tehri Hydro & Pumped Storage Complex",
    "location": "New Tehri / Garhwal",
    "state": "Uttarakhand",
    "riverBasin": "Bhagirathi River",
    "coordinates": [
      30.37,
      78.48
    ],
    "region": "NR",
    "type": "HYDRO_PSP",
    "subtype": "Peaking & Pumped Storage Plant",
    "capacityMw": 2400,
    "currentGenMw": 1450,
    "minDispatchMw": 400,
    "maxDispatchMw": 2400,
    "voltageKv": 400,
    "unitsCount": 8,
    "unitDetails": "4 x 250 MW HPP + 4 x 250 MW Reversible PSP",
    "fuelType": "Hydro",
    "operator": "THDC India Limited",
    "description": "India's highest dam (260.5m) and primary AGC secondary frequency control asset for the Northern Regional Grid.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-DELHI"
  },
  {
    "id": "SRC-KOYNA",
    "name": "Koyna Hydroelectric Project",
    "location": "Koynanagar / Satara District",
    "state": "Maharashtra",
    "riverBasin": "Koyna River",
    "coordinates": [
      17.4,
      73.75
    ],
    "region": "WR",
    "type": "HYDRO_DAM",
    "subtype": "High-Head Underground Peaking Complex",
    "capacityMw": 1960,
    "currentGenMw": 1250,
    "minDispatchMw": 200,
    "maxDispatchMw": 1960,
    "voltageKv": 400,
    "unitsCount": 16,
    "unitDetails": "Stage I-IV Underground Pelton & Francis Turbines",
    "fuelType": "Hydro",
    "operator": "Mahagenco",
    "description": "Largest completed hydroelectric plant in India providing rapid peaking power to Mumbai & Pune grid.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-MUMBAI"
  },
  {
    "id": "SRC-BHAKRA",
    "name": "Bhakra Nangal Hydroelectric Project",
    "location": "Bilaspur / Nangal",
    "state": "Himachal Pradesh",
    "riverBasin": "Sutlej River",
    "coordinates": [
      31.41,
      76.43
    ],
    "region": "NR",
    "type": "HYDRO_DAM",
    "subtype": "Concrete Gravity Dam Complex",
    "capacityMw": 1325,
    "currentGenMw": 1150,
    "minDispatchMw": 300,
    "maxDispatchMw": 1325,
    "voltageKv": 400,
    "unitsCount": 10,
    "unitDetails": "5 x 108 MW Left Bank + 5 x 157 MW Right Bank Turbines",
    "fuelType": "Hydro",
    "operator": "Bhakra Beas Management Board (BBMB)",
    "description": "Historic landmark gravity dam on Sutlej river supplying baseline hydro dispatch to Punjab Haryana Rajasthan and Delhi.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-DELHI"
  },
  {
    "id": "SRC-NATHPA",
    "name": "Nathpa Jhakri Hydroelectric Station",
    "location": "Shimla / Kinnaur District",
    "state": "Himachal Pradesh",
    "riverBasin": "Satluj River",
    "coordinates": [
      31.56,
      77.97
    ],
    "region": "NR",
    "type": "HYDRO_DAM",
    "subtype": "Run-of-the-River Underground Station",
    "capacityMw": 1500,
    "currentGenMw": 1380,
    "minDispatchMw": 250,
    "maxDispatchMw": 1500,
    "voltageKv": 400,
    "unitsCount": 6,
    "unitDetails": "6 x 250 MW Vertical Francis Turbines",
    "fuelType": "Hydro",
    "operator": "SJVN Limited (Govt of India & HP)",
    "description": "Country's largest underground run-of-the-river hydroelectric plant featuring one of the world's deepest desilting chambers.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-DELHI"
  },
  {
    "id": "SRC-SRISAILAM",
    "name": "Srisailam Hydro Power Complex",
    "location": "Srisailam / Kurnool & Nagarkurnool",
    "state": "Andhra Pradesh",
    "riverBasin": "Krishna River",
    "coordinates": [
      16.08,
      78.89
    ],
    "region": "SR",
    "type": "HYDRO_PSP",
    "subtype": "Left & Right Bank Peaking Complex",
    "capacityMw": 1670,
    "currentGenMw": 1220,
    "minDispatchMw": 200,
    "maxDispatchMw": 1670,
    "voltageKv": 400,
    "unitsCount": 13,
    "unitDetails": "6 x 150 MW Reversible Left Bank PSP + 7 x 110 MW Right Bank Turbines",
    "fuelType": "Hydro",
    "operator": "APGENCO / TSGENCO",
    "description": "Deep gorge reservoir dam on Krishna river operating massive reversible Francis pump-turbines for Southern grid frequency stabilization.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-HYDERABAD"
  },
  {
    "id": "SRC-NAGARJUNA",
    "name": "Nagarjuna Sagar Hydroelectric Station",
    "location": "Nalgonda & Guntur Districts",
    "state": "Telangana",
    "riverBasin": "Krishna River",
    "coordinates": [
      16.57,
      79.31
    ],
    "region": "SR",
    "type": "HYDRO_PSP",
    "subtype": "Masonry Gravity Dam & Pumped Storage",
    "capacityMw": 816,
    "currentGenMw": 680,
    "minDispatchMw": 100,
    "maxDispatchMw": 816,
    "voltageKv": 220,
    "unitsCount": 8,
    "unitDetails": "1 x 110 MW Conventional + 7 x 100 MW Reversible Francis Turbines",
    "fuelType": "Hydro",
    "operator": "TSGENCO",
    "description": "Pioneering pumped storage hydro installation in Southern India providing rapid sub-minute black-start capability.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-HYDERABAD"
  },
  {
    "id": "SRC-IDUKKI",
    "name": "Idukki Hydroelectric Project",
    "location": "Vazhathope / Idukki District",
    "state": "Kerala",
    "riverBasin": "Periyar River",
    "coordinates": [
      9.85,
      76.97
    ],
    "region": "SR",
    "type": "HYDRO_DAM",
    "subtype": "Double Curvature Arch Dam & Underground Station",
    "capacityMw": 780,
    "currentGenMw": 620,
    "minDispatchMw": 100,
    "maxDispatchMw": 780,
    "voltageKv": 220,
    "unitsCount": 6,
    "unitDetails": "6 x 130 MW High-Head Pelton Wheel Turbines (Moolamattom)",
    "fuelType": "Hydro",
    "operator": "Kerala State Electricity Board (KSEB)",
    "description": "Iconic double-curvature thin arch dam constructed between Kuravan and Kurathi granite hills powering Kerala's industrial heartland.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-KOCHI"
  },
  {
    "id": "SRC-INDIRA-SAGAR",
    "name": "Indira Sagar Hydro Power Project",
    "location": "Narmadanagar / Khandwa District",
    "state": "Madhya Pradesh",
    "riverBasin": "Narmada River",
    "coordinates": [
      22.28,
      76.47
    ],
    "region": "WR",
    "type": "HYDRO_DAM",
    "subtype": "Concrete Gravity Reservoir Station",
    "capacityMw": 1000,
    "currentGenMw": 840,
    "minDispatchMw": 150,
    "maxDispatchMw": 1000,
    "voltageKv": 400,
    "unitsCount": 8,
    "unitDetails": "8 x 125 MW Francis Turbines",
    "fuelType": "Hydro",
    "operator": "Narmada Hydroelectric Development Corp (NHDC / NHPC)",
    "description": "Largest reservoir capacity dam in India with 12.22 billion cubic meters of storage supplying dispatchable hydro balancing to Western grid.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-INDORE"
  },
  {
    "id": "SRC-SUBANSIRI",
    "name": "Subansiri Lower Hydroelectric Project",
    "location": "Gerukamukh / Dhemaji & Lower Subansiri",
    "state": "Arunachal Pradesh",
    "riverBasin": "Subansiri River",
    "coordinates": [
      27.55,
      94.26
    ],
    "region": "NER",
    "type": "HYDRO_DAM",
    "subtype": "Run-of-the-River Mega Dam",
    "capacityMw": 2000,
    "currentGenMw": 1400,
    "minDispatchMw": 300,
    "maxDispatchMw": 2000,
    "voltageKv": 400,
    "unitsCount": 8,
    "unitDetails": "8 x 250 MW Francis Turbines",
    "fuelType": "Hydro",
    "operator": "NHPC Limited",
    "description": "Largest hydroelectric project conceived in Northeast India providing high-capacity clean balancing to the national grid via ±800kV HVDC.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-GUWAHATI"
  },
  {
    "id": "SRC-PURULIA-PSP",
    "name": "Purulia Pumped Storage Project",
    "location": "Ayodhya Hills / Purulia District",
    "state": "West Bengal",
    "riverBasin": "Kistobazar Nallah",
    "coordinates": [
      23.19,
      86.09
    ],
    "region": "ER",
    "type": "HYDRO_PSP",
    "subtype": "Pure Closed-Loop Pumped Storage",
    "capacityMw": 900,
    "currentGenMw": 720,
    "minDispatchMw": 0,
    "maxDispatchMw": 900,
    "voltageKv": 400,
    "unitsCount": 4,
    "unitDetails": "4 x 225 MW Reversible Pump-Turbine Motor-Generators",
    "fuelType": "Hydro",
    "operator": "West Bengal State Electricity Distribution Co (WBSEDCL)",
    "description": "Premier 900 MW peaking pumped storage asset in Eastern India providing round-the-clock spinning reserves and renewable absorption.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-KOLKATA"
  },
  {
    "id": "SRC-KAKRAPAR",
    "name": "Kakrapar Atomic Power Station (KAPS)",
    "location": "Vyara / Mandvi / Tapi District",
    "state": "Gujarat",
    "riverBasin": "Tapi River",
    "coordinates": [
      21.24,
      73.35
    ],
    "region": "WR",
    "type": "NUCLEAR_BASE",
    "subtype": "Pressurized Heavy Water Reactor (PHWR)",
    "capacityMw": 1840,
    "currentGenMw": 1800,
    "minDispatchMw": 1600,
    "maxDispatchMw": 1840,
    "voltageKv": 400,
    "unitsCount": 4,
    "unitDetails": "2 x 220 MWe + 2 x 700 MWe First Indigenous PHWRs",
    "fuelType": "Natural Uranium (UO2)",
    "operator": "Nuclear Power Corporation of India Limited (NPCIL)",
    "description": "India's landmark nuclear power facility hosting the nation's first twin 700 MWe indigenous PHWR reactors providing continuous zero-carbon baseload.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-HAZIRA"
  },
  {
    "id": "SRC-TARAPUR",
    "name": "Tarapur Atomic Power Station (TAPS)",
    "location": "Boisar / Palghar District",
    "state": "Maharashtra",
    "riverBasin": "Arabian Sea Coast",
    "coordinates": [
      19.83,
      72.65
    ],
    "region": "WR",
    "type": "NUCLEAR_BASE",
    "subtype": "BWR & PHWR Nuclear Plant",
    "capacityMw": 1400,
    "currentGenMw": 1350,
    "minDispatchMw": 1200,
    "maxDispatchMw": 1400,
    "voltageKv": 400,
    "unitsCount": 4,
    "unitDetails": "2 x 160 MW BWR + 2 x 540 MW PHWR",
    "fuelType": "Enriched & Natural Uranium",
    "operator": "NPCIL",
    "description": "Oldest commercial nuclear power station in India feeding Mumbai Metropolitan Region and industrial Thane-Belapur belt.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-MUMBAI"
  },
  {
    "id": "SRC-KUDANKULAM",
    "name": "Kudankulam Nuclear Power Plant (KKNPP)",
    "location": "Radhapuram / Tirunelveli District",
    "state": "Tamil Nadu",
    "riverBasin": "Gulf of Mannar Coast",
    "coordinates": [
      8.17,
      77.71
    ],
    "region": "SR",
    "type": "NUCLEAR_BASE",
    "subtype": "VVER-1000 Pressurized Water Reactor",
    "capacityMw": 2000,
    "currentGenMw": 1980,
    "minDispatchMw": 1800,
    "maxDispatchMw": 2000,
    "voltageKv": 400,
    "unitsCount": 2,
    "unitDetails": "2 x 1000 MW AES-92 VVER-1000 (Light Water)",
    "fuelType": "Enriched Uranium (U-235)",
    "operator": "NPCIL & Rosatom",
    "description": "Highest capacity nuclear generation station in India supplying ultra-stable zero-carbon baseload power to Southern Grid.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-BLR"
  },
  {
    "id": "SRC-KAIGA",
    "name": "Kaiga Generating Station",
    "location": "Kaiga / Karwar / Uttara Kannada",
    "state": "Karnataka",
    "riverBasin": "Kali River",
    "coordinates": [
      14.86,
      74.43
    ],
    "region": "SR",
    "type": "NUCLEAR_BASE",
    "subtype": "Pressurized Heavy Water Reactor (PHWR)",
    "capacityMw": 880,
    "currentGenMw": 850,
    "minDispatchMw": 750,
    "maxDispatchMw": 880,
    "voltageKv": 400,
    "unitsCount": 4,
    "unitDetails": "4 x 220 MWe Horizontal Pressure Tube PHWRs",
    "fuelType": "Natural Uranium (UO2)",
    "operator": "NPCIL",
    "description": "World-record-holding nuclear facility with Unit-1 operating continuously without shutdown for 962 days.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-BLR"
  },
  {
    "id": "SRC-RAPS",
    "name": "Rajasthan Atomic Power Station (RAPS)",
    "location": "Rawatbhata / Chittorgarh District",
    "state": "Rajasthan",
    "riverBasin": "Chambal River (Rana Pratap Sagar)",
    "coordinates": [
      24.87,
      75.6
    ],
    "region": "NR",
    "type": "NUCLEAR_BASE",
    "subtype": "Pressurized Heavy Water Reactor (PHWR)",
    "capacityMw": 1180,
    "currentGenMw": 1120,
    "minDispatchMw": 950,
    "maxDispatchMw": 1180,
    "voltageKv": 400,
    "unitsCount": 6,
    "unitDetails": "1 x 100 MW + 1 x 200 MW + 4 x 220 MW PHWRs",
    "fuelType": "Natural Uranium (UO2)",
    "operator": "NPCIL",
    "description": "Pioneering PHWR nuclear energy center in northwestern India supplying baseload power across Rajasthan Haryana and Punjab.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-JAIPUR"
  },
  {
    "id": "SRC-MAPS",
    "name": "Madras Atomic Power Station (MAPS)",
    "location": "Kalpakkam / Chengalpattu District",
    "state": "Tamil Nadu",
    "riverBasin": "Bay of Bengal Coast",
    "coordinates": [
      12.55,
      80.17
    ],
    "region": "SR",
    "type": "NUCLEAR_BASE",
    "subtype": "Indigenous PHWR Coastal Station",
    "capacityMw": 440,
    "currentGenMw": 410,
    "minDispatchMw": 350,
    "maxDispatchMw": 440,
    "voltageKv": 230,
    "unitsCount": 2,
    "unitDetails": "2 x 220 MWe Indigenous PHWRs",
    "fuelType": "Natural Uranium (UO2)",
    "operator": "NPCIL",
    "description": "India's first fully indigenous nuclear station equipped with undersea water intake tunnels for condenser cooling.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-CHENNAI"
  },
  {
    "id": "SRC-NAPS",
    "name": "Narora Atomic Power Station (NAPS)",
    "location": "Narora / Bulandshahr District",
    "state": "Uttar Pradesh",
    "riverBasin": "Ganga River",
    "coordinates": [
      28.16,
      78.41
    ],
    "region": "NR",
    "type": "NUCLEAR_BASE",
    "subtype": "Pressurized Heavy Water Reactor (PHWR)",
    "capacityMw": 440,
    "currentGenMw": 420,
    "minDispatchMw": 380,
    "maxDispatchMw": 440,
    "voltageKv": 220,
    "unitsCount": 2,
    "unitDetails": "2 x 220 MWe Standardized PHWRs",
    "fuelType": "Natural Uranium (UO2)",
    "operator": "NPCIL",
    "description": "Northern inland nuclear installation with double containment structures providing firm green baseload to Western UP and Delhi NCR.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-DELHI"
  },
  {
    "id": "SRC-BHADLA",
    "name": "Bhadla Solar Park",
    "location": "Phalodi / Jodhpur District",
    "state": "Rajasthan",
    "riverBasin": "",
    "coordinates": [
      27.53,
      71.91
    ],
    "region": "NR",
    "type": "SOLAR_RE",
    "subtype": "Utility-Scale Photovoltaic Park",
    "capacityMw": 2245,
    "currentGenMw": 1840,
    "minDispatchMw": 0,
    "maxDispatchMw": 2245,
    "voltageKv": 765,
    "unitsCount": 18,
    "unitDetails": "Multi-developer utility photovoltaic modules",
    "fuelType": "Solar PV",
    "operator": "RSDCL / NTPC / Adani / Saurya Urja",
    "description": "One of the world's largest solar parks across 14000 acres feeding the Northern Green Energy Corridor with 765kV EHV lines.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-DELHI"
  },
  {
    "id": "SRC-KHAVDA",
    "name": "Khavda Renewable Energy Park",
    "location": "Rann of Kutch (Vighakot)",
    "state": "Gujarat",
    "riverBasin": "",
    "coordinates": [
      23.85,
      69.73
    ],
    "region": "WR",
    "type": "HYBRID_RE",
    "subtype": "Hybrid Wind-Solar Mega Installation",
    "capacityMw": 3000,
    "currentGenMw": 2420,
    "minDispatchMw": 0,
    "maxDispatchMw": 3000,
    "voltageKv": 765,
    "unitsCount": 24,
    "unitDetails": "Hybrid utility bifacial solar arrays + 3.0 MW onshore wind turbines",
    "fuelType": "Hybrid Solar & Wind",
    "operator": "Adani Green Energy / NTPC REL",
    "description": "Mega hybrid wind-solar park providing Western-to-Northern power wheeling via 765kV double-circuit lines.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-MUMBAI"
  },
  {
    "id": "SRC-CHARANKA",
    "name": "Charanka Solar Park (Gujarat Solar Park-1)",
    "location": "Santalpur / Patan District",
    "state": "Gujarat",
    "riverBasin": "",
    "coordinates": [
      23.91,
      71.19
    ],
    "region": "WR",
    "type": "SOLAR_RE",
    "subtype": "Multi-Developer Solar Park",
    "capacityMw": 790,
    "currentGenMw": 680,
    "minDispatchMw": 0,
    "maxDispatchMw": 790,
    "voltageKv": 400,
    "unitsCount": 8,
    "unitDetails": "Multi-developer thin film & crystalline silicon modules",
    "fuelType": "Solar PV",
    "operator": "Gujarat Power Corporation Limited (GPCL)",
    "description": "Pioneering utility-scale solar park in India deployed across 5384 acres in Patan.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-AHMEDABAD"
  },
  {
    "id": "SRC-PAVAGADA",
    "name": "Pavagada Solar Park (Shakti Sthala)",
    "location": "Pavagada / Tumakuru District",
    "state": "Karnataka",
    "riverBasin": "",
    "coordinates": [
      14.1,
      77.27
    ],
    "region": "SR",
    "type": "SOLAR_RE",
    "subtype": "Utility-Scale Photovoltaic Park",
    "capacityMw": 2050,
    "currentGenMw": 1710,
    "minDispatchMw": 0,
    "maxDispatchMw": 2050,
    "voltageKv": 400,
    "unitsCount": 16,
    "unitDetails": "8 x 250 MW blocks utility PV arrays",
    "fuelType": "Solar PV",
    "operator": "Karnataka Solar Power Development Corp (KSPDCL)",
    "description": "Southern Regional Grid anchor solar facility powering Bengaluru and southern industrial corridors.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-BLR"
  },
  {
    "id": "SRC-MUPPANDAL",
    "name": "Muppandal Wind Energy Complex",
    "location": "Aralvaimozhi / Kanyakumari District",
    "state": "Tamil Nadu",
    "riverBasin": "",
    "coordinates": [
      8.26,
      77.54
    ],
    "region": "SR",
    "type": "WIND_RE",
    "subtype": "Onshore Wind Turbine Farm",
    "capacityMw": 1500,
    "currentGenMw": 1120,
    "minDispatchMw": 100,
    "maxDispatchMw": 1500,
    "voltageKv": 400,
    "unitsCount": 20,
    "unitDetails": "Over 3000 mixed capacity onshore wind turbines",
    "fuelType": "Wind Kinetic",
    "operator": "TANGEDCO / Private IPPs",
    "description": "Historic high-capacity wind corridor utilizing seasonal southwest monsoonal winds through the Palakkad and Aralvaimozhi mountain gaps.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-CHENNAI"
  },
  {
    "id": "SRC-REWA",
    "name": "Rewa Ultra Mega Solar",
    "location": "Gurh Tehsil / Rewa District",
    "state": "Madhya Pradesh",
    "riverBasin": "",
    "coordinates": [
      24.47,
      81.57
    ],
    "region": "WR",
    "type": "SOLAR_RE",
    "subtype": "Ground-Mounted Photovoltaic Project",
    "capacityMw": 750,
    "currentGenMw": 660,
    "minDispatchMw": 0,
    "maxDispatchMw": 750,
    "voltageKv": 400,
    "unitsCount": 3,
    "unitDetails": "3 x 250 MW Grid Connected Solar Units (Mahindra / ACME / Solenergi)",
    "fuelType": "Solar PV",
    "operator": "Rewa Ultra Mega Solar Limited (RUMSL / SECI)",
    "description": "Landmark 750 MW solar park supplying 24% of its generated green electricity to the Delhi Metro Rail Corporation (DMRC).",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-BHOPAL"
  },
  {
    "id": "SRC-KURNOOL",
    "name": "Kurnool Ultra Mega Solar Park",
    "location": "Gani & Sakunala / Kurnool District",
    "state": "Andhra Pradesh",
    "riverBasin": "",
    "coordinates": [
      15.68,
      78.28
    ],
    "region": "SR",
    "type": "SOLAR_RE",
    "subtype": "Integrated Mega Solar Park",
    "capacityMw": 1000,
    "currentGenMw": 880,
    "minDispatchMw": 0,
    "maxDispatchMw": 1000,
    "voltageKv": 400,
    "unitsCount": 4,
    "unitDetails": "4 x 250 MW Solar PV Plant Blocks (NTPC / Softbank / Greenko)",
    "fuelType": "Solar PV",
    "operator": "Andhra Pradesh Solar Power Corp (APSPCL)",
    "description": "Spread over 5932 acres in Kurnool generating clean solar power feeding the 400kV Southern pooling substation.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-HYDERABAD"
  },
  {
    "id": "SRC-KAMUTHI",
    "name": "Kamuthi Solar Power Project",
    "location": "Kamuthi / Ramanathapuram District",
    "state": "Tamil Nadu",
    "riverBasin": "",
    "coordinates": [
      9.35,
      78.39
    ],
    "region": "SR",
    "type": "SOLAR_RE",
    "subtype": "Single-Location Solar Plant",
    "capacityMw": 648,
    "currentGenMw": 580,
    "minDispatchMw": 0,
    "maxDispatchMw": 648,
    "voltageKv": 230,
    "unitsCount": 5,
    "unitDetails": "2.5 million solar modules across 2500 acres",
    "fuelType": "Solar PV",
    "operator": "Adani Green Energy Limited",
    "description": "Commissioned in a record 8 months as one of the world's largest single-location solar power stations at the time.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-MADURAI"
  },
  {
    "id": "SRC-JAISALMER",
    "name": "Jaisalmer Wind Park",
    "location": "Amarsagar / Jaisalmer District",
    "state": "Rajasthan",
    "riverBasin": "",
    "coordinates": [
      26.91,
      70.9
    ],
    "region": "NR",
    "type": "WIND_RE",
    "subtype": "High-Yield Desert Wind Farm",
    "capacityMw": 1064,
    "currentGenMw": 840,
    "minDispatchMw": 50,
    "maxDispatchMw": 1064,
    "voltageKv": 400,
    "unitsCount": 12,
    "unitDetails": "Multiple wind turbine arrays ranging from 1.5 MW to 2.1 MW",
    "fuelType": "Wind Kinetic",
    "operator": "Suzlon Energy & Multiple IPPs",
    "description": "India's largest continuous onshore wind park situated in the Thar Desert harnessing hot westerly desert winds.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-JAIPUR"
  },
  {
    "id": "SRC-DHOLERA",
    "name": "Dholera SIR Ultra Mega Solar Park",
    "location": "Dholera Special Investment Region",
    "state": "Gujarat",
    "riverBasin": "Gulf of Khambhat",
    "coordinates": [
      22.25,
      72.19
    ],
    "region": "WR",
    "type": "SOLAR_RE",
    "subtype": "Coastal Saline Land Solar Park",
    "capacityMw": 1000,
    "currentGenMw": 820,
    "minDispatchMw": 0,
    "maxDispatchMw": 1000,
    "voltageKv": 400,
    "unitsCount": 4,
    "unitDetails": "Utility bifacial trackers and crystalline modules",
    "fuelType": "Solar PV",
    "operator": "Gujarat Power Corporation Limited (GPCL / Tata / Torrent)",
    "description": "Massive planned 4400 MW solar facility with Phase 1 operational on non-agricultural coastal saline land.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-AHMEDABAD"
  },
  {
    "id": "SRC-ANANTHAPURAMU",
    "name": "Ananthapuramu Ultra Mega Solar Park",
    "location": "NP Kunta / Ananthapuramu District",
    "state": "Andhra Pradesh",
    "riverBasin": "",
    "coordinates": [
      14.97,
      77.45
    ],
    "region": "SR",
    "type": "SOLAR_RE",
    "subtype": "Grid-Scale Solar Power Park",
    "capacityMw": 1500,
    "currentGenMw": 1280,
    "minDispatchMw": 0,
    "maxDispatchMw": 1500,
    "voltageKv": 400,
    "unitsCount": 6,
    "unitDetails": "6 x 250 MW Solar Power Blocks",
    "fuelType": "Solar PV",
    "operator": "APSPCL / NTPC",
    "description": "Sprawling utility solar installation in Rayalaseema region bolstering Andhra Pradesh and southern state green energy quotas.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-BLR"
  },
  {
    "id": "SRC-SINGRAULI",
    "name": "Singrauli Super Thermal Power Station",
    "location": "Shaktinagar / Sonebhadra District",
    "state": "Uttar Pradesh",
    "riverBasin": "Rihand Reservoir",
    "coordinates": [
      24.1,
      82.67
    ],
    "region": "NR",
    "type": "THERMAL_COAL",
    "subtype": "Pithead Super Thermal Plant",
    "capacityMw": 2000,
    "currentGenMw": 1880,
    "minDispatchMw": 1100,
    "maxDispatchMw": 2000,
    "voltageKv": 500,
    "unitsCount": 7,
    "unitDetails": "5 x 200 MW + 2 x 500 MW Pulverized Coal Units",
    "fuelType": "Domestic Bituminous Coal",
    "operator": "NTPC Limited",
    "description": "Flagship pithead power station connected via India's pioneering ±500 kV HVDC Rihand-Dadri transmission link.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-DELHI"
  },
  {
    "id": "SRC-MUNDRA",
    "name": "Mundra Thermal Power Station",
    "location": "Mundra Port / Kutch",
    "state": "Gujarat",
    "riverBasin": "Gulf of Kutch Coast",
    "coordinates": [
      22.82,
      69.52
    ],
    "region": "WR",
    "type": "THERMAL_COAL",
    "subtype": "Coastal Supercritical Coal Plant",
    "capacityMw": 4620,
    "currentGenMw": 3950,
    "minDispatchMw": 2200,
    "maxDispatchMw": 4620,
    "voltageKv": 500,
    "unitsCount": 9,
    "unitDetails": "4 x 330 MW Subcritical + 5 x 660 MW Supercritical Boilers",
    "fuelType": "Imported Coal",
    "operator": "Adani Power Limited",
    "description": "Massive coastal supercritical coal-fired generation hub connected to western and northern grids with dedicated HVDC transmission.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-SANAND"
  },
  {
    "id": "SRC-WANAKBORI",
    "name": "Wanakbori Thermal Power Station (WTPS)",
    "location": "Wanakbori / Kheda District",
    "state": "Gujarat",
    "riverBasin": "Mahi River",
    "coordinates": [
      22.88,
      73.36
    ],
    "region": "WR",
    "type": "THERMAL_COAL",
    "subtype": "Inland Supercritical Coal Power Station",
    "capacityMw": 2270,
    "currentGenMw": 1920,
    "minDispatchMw": 1000,
    "maxDispatchMw": 2270,
    "voltageKv": 400,
    "unitsCount": 8,
    "unitDetails": "7 x 210 MW Subcritical + 1 x 800 MW Supercritical Unit",
    "fuelType": "Domestic Coal",
    "operator": "GSECL",
    "description": "Major base-load coal-fired station on the banks of Mahi river providing grid inertia and baseload stability to central Gujarat.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-AHMEDABAD"
  },
  {
    "id": "SRC-VINDHYACHAL",
    "name": "Vindhyachal Super Thermal Power Station",
    "location": "Singrauli / Vindhyanagar",
    "state": "Madhya Pradesh",
    "riverBasin": "Rihand Reservoir",
    "coordinates": [
      24.09,
      82.67
    ],
    "region": "WR",
    "type": "THERMAL_COAL",
    "subtype": "Largest Thermal Power Plant in India",
    "capacityMw": 4760,
    "currentGenMw": 4280,
    "minDispatchMw": 2400,
    "maxDispatchMw": 4760,
    "voltageKv": 400,
    "unitsCount": 13,
    "unitDetails": "6 x 210 MW + 7 x 500 MW Pulverized Coal Units",
    "fuelType": "Coal (NCL Pithead)",
    "operator": "NTPC Limited",
    "description": "India's largest thermal power station with 4760 MW installed capacity operating at high plant load factor (PLF) supporting national grid inertia.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-BHOPAL"
  },
  {
    "id": "SRC-TALCHER",
    "name": "Talcher Super Thermal Power Station (Kaniha)",
    "location": "Kaniha / Angul District",
    "state": "Odisha",
    "riverBasin": "Brahmani River / Samal Barrage",
    "coordinates": [
      20.91,
      85.08
    ],
    "region": "ER",
    "type": "THERMAL_COAL",
    "subtype": "Pithead Supercritical Complex",
    "capacityMw": 3000,
    "currentGenMw": 2780,
    "minDispatchMw": 1500,
    "maxDispatchMw": 3000,
    "voltageKv": 500,
    "unitsCount": 6,
    "unitDetails": "6 x 500 MW Coal-Fired Steam Turbine Generating Units",
    "fuelType": "Coal (MCL Pithead)",
    "operator": "NTPC Limited",
    "description": "Key baseload station linked to the Southern Region via the iconic ±500 kV Talcher-Kolar HVDC bipole corridor.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-BHUBANESWAR"
  },
  {
    "id": "SRC-SIPAT",
    "name": "Sipat Super Thermal Power Station (Rajiv Gandhi)",
    "location": "Sipat / Bilaspur District",
    "state": "Chhattisgarh",
    "riverBasin": "Hasdeo Barrage",
    "coordinates": [
      22.13,
      82.29
    ],
    "region": "WR",
    "type": "THERMAL_COAL",
    "subtype": "Supercritical Coal-Fired Station",
    "capacityMw": 2980,
    "currentGenMw": 2650,
    "minDispatchMw": 1400,
    "maxDispatchMw": 2980,
    "voltageKv": 765,
    "unitsCount": 5,
    "unitDetails": "3 x 660 MW Supercritical + 2 x 500 MW Subcritical Units",
    "fuelType": "Domestic Coal (SECL)",
    "operator": "NTPC Limited",
    "description": "First supercritical 765kV connected power project in India distributing stable baseload power to Western states.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-RAIPUR"
  },
  {
    "id": "SRC-RAMAGUNDAM",
    "name": "Ramagundam Super Thermal Power Station",
    "location": "Peddapalli District",
    "state": "Telangana",
    "riverBasin": "Godavari River",
    "coordinates": [
      18.75,
      79.51
    ],
    "region": "SR",
    "type": "THERMAL_COAL",
    "subtype": "Pithead Base Thermal Station",
    "capacityMw": 2600,
    "currentGenMw": 2350,
    "minDispatchMw": 1300,
    "maxDispatchMw": 2600,
    "voltageKv": 400,
    "unitsCount": 7,
    "unitDetails": "3 x 200 MW + 4 x 500 MW Generating Units + 100 MW Floating Solar",
    "fuelType": "Coal (SCCL)",
    "operator": "NTPC Limited",
    "description": "Premier power producer in South India also hosting India's largest 100 MW floating solar PV installation on its water reservoir.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-HYDERABAD"
  },
  {
    "id": "SRC-KUDGI",
    "name": "Kudgi Super Thermal Power Project",
    "location": "Kudgi / Basavana Bagewadi / Vijayapura",
    "state": "Karnataka",
    "riverBasin": "Almatti Dam (Krishna River)",
    "coordinates": [
      16.71,
      75.88
    ],
    "region": "SR",
    "type": "THERMAL_COAL",
    "subtype": "Supercritical Thermal Power Station",
    "capacityMw": 2400,
    "currentGenMw": 2150,
    "minDispatchMw": 1200,
    "maxDispatchMw": 2400,
    "voltageKv": 400,
    "unitsCount": 3,
    "unitDetails": "3 x 800 MW Supercritical Steam Generating Units",
    "fuelType": "Domestic Coal",
    "operator": "NTPC Limited",
    "description": "State-of-the-art 800 MW supercritical units serving peak industrial demands in Karnataka and Southern grid.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-BLR"
  },
  {
    "id": "SRC-BARH",
    "name": "Barh Super Thermal Power Station",
    "location": "Barh / Patna District",
    "state": "Bihar",
    "riverBasin": "Ganga River",
    "coordinates": [
      25.48,
      85.71
    ],
    "region": "ER",
    "type": "THERMAL_COAL",
    "subtype": "Supercritical Coal Plant",
    "capacityMw": 3300,
    "currentGenMw": 2980,
    "minDispatchMw": 1600,
    "maxDispatchMw": 3300,
    "voltageKv": 400,
    "unitsCount": 5,
    "unitDetails": "5 x 660 MW Supercritical Generating Sets",
    "fuelType": "Domestic Coal",
    "operator": "NTPC Limited",
    "description": "High-capacity supercritical generating complex on the Ganges river delivering bulk power to Bihar Eastern and Northern grids.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-PATNA"
  },
  {
    "id": "SRC-KORBA",
    "name": "Korba Super Thermal Power Plant",
    "location": "Jmnipali / Korba District",
    "state": "Chhattisgarh",
    "riverBasin": "Hasdeo River",
    "coordinates": [
      22.38,
      82.68
    ],
    "region": "WR",
    "type": "THERMAL_COAL",
    "subtype": "Pithead Super Thermal Station",
    "capacityMw": 2600,
    "currentGenMw": 2380,
    "minDispatchMw": 1300,
    "maxDispatchMw": 2600,
    "voltageKv": 400,
    "unitsCount": 7,
    "unitDetails": "3 x 200 MW + 4 x 500 MW Generating Units",
    "fuelType": "Domestic Coal (Gevra/Dipka Mines)",
    "operator": "NTPC Limited",
    "description": "Consistently recognized as one of the lowest-cost baseload power stations in India with ultra-high plant load factors.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-RAIPUR"
  },
  {
    "id": "SRC-DADRI",
    "name": "NTPC Dadri Super Thermal & Gas Power Complex",
    "location": "Vidyut Nagar / Gautam Buddha Nagar",
    "state": "Uttar Pradesh",
    "riverBasin": "",
    "coordinates": [
      28.59,
      77.55
    ],
    "region": "NR",
    "type": "THERMAL_COAL",
    "subtype": "Coal & Gas Combined Cycle Complex",
    "capacityMw": 2637,
    "currentGenMw": 2350,
    "minDispatchMw": 1200,
    "maxDispatchMw": 2637,
    "voltageKv": 400,
    "unitsCount": 10,
    "unitDetails": "4 x 210 MW + 2 x 490 MW Coal + 829 MW Gas Turbine Units",
    "fuelType": "Coal & Natural Gas",
    "operator": "NTPC Limited",
    "description": "Crucial baseload and fast-ramping gas turbine station providing uninterruptible round-the-clock power to the National Capital Delhi.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-DELHI"
  },
  {
    "id": "SRC-FARAKKA",
    "name": "Farakka Super Thermal Power Station",
    "location": "Nabarun / Murshidabad District",
    "state": "West Bengal",
    "riverBasin": "Farakka Feeder Canal (Ganga)",
    "coordinates": [
      24.77,
      87.89
    ],
    "region": "ER",
    "type": "THERMAL_COAL",
    "subtype": "Pithead Thermal Station",
    "capacityMw": 2100,
    "currentGenMw": 1850,
    "minDispatchMw": 1000,
    "maxDispatchMw": 2100,
    "voltageKv": 400,
    "unitsCount": 6,
    "unitDetails": "3 x 200 MW + 2 x 500 MW + 1 x 500 MW Units",
    "fuelType": "Coal (Rajmahal Mines)",
    "operator": "NTPC Limited",
    "description": "Vital thermal baseload anchor connecting Eastern and Northeastern regional transmission systems.",
    "status": "ONLINE",
    "curtailed": false,
    "corridorTarget": "SNK-KOLKATA"
  }
];
