// Real-World Indian Electricity Sources: Hydro Dams, Nuclear, Solar Parks, Wind Complexes & Thermal Plants
// Sourced from Central Electricity Authority (CEA), Grid-India (POSOCO), NPCIL, NHPC, GUVNL & State Gencos.

export const ELECTRICITY_SOURCES = [
  // --- 1. HYDROELECTRIC DAMS & PUMPED STORAGE PLANTS ---
  {
    id: "SRC-UKAI",
    name: "Ukai Dam Hydro Power Plant (Vallabh Sagar)",
    location: "Songadh / Tapi District",
    state: "Gujarat",
    riverBasin: "Tapi River",
    coordinates: [21.25, 73.58],
    region: "WR",
    type: "HYDRO_DAM",
    subtype: "Storage Reservoir Hydro",
    capacityMw: 300,
    currentGenMw: 240,
    minDispatchMw: 50,
    maxDispatchMw: 300,
    voltageKv: 220,
    units: [
      { unitNo: 1, capacityMw: 75, type: "Francis Turbine", status: "ONLINE" },
      { unitNo: 2, capacityMw: 75, type: "Francis Turbine", status: "ONLINE" },
      { unitNo: 3, capacityMw: 75, type: "Francis Turbine", status: "ONLINE" },
      { unitNo: 4, capacityMw: 75, type: "Francis Turbine", status: "STANDBY" }
    ],
    operatingHeadMeters: 57.0,
    fullReservoirLevelMeters: 105.15,
    operator: "Gujarat State Electricity Corporation Limited (GSECL)",
    description: "Multipurpose earth-cum-masonry dam on Tapi river. Provides rapid peaking power, irrigation, and flood mitigation to Surat downstream.",
    status: "ONLINE",
    curtailed: false,
    corridorTarget: "SNK-SURAT"
  },
  {
    id: "SRC-SARDAR-SAROVAR",
    name: "Sardar Sarovar Dam Hydro Project (Narmada Hydro)",
    location: "Kevadia / Narmada District",
    state: "Gujarat",
    riverBasin: "Narmada River",
    coordinates: [21.83, 73.75],
    region: "WR",
    type: "HYDRO_DAM",
    subtype: "Run-of-River with Pondage / Underground RBPH",
    capacityMw: 1450,
    currentGenMw: 1180,
    minDispatchMw: 250,
    maxDispatchMw: 1450,
    voltageKv: 400,
    units: [
      { powerhouse: "River Bed Power House (RBPH)", units: "6 x 200 MW Reversible Francis Turbines", totalMw: 1200 },
      { powerhouse: "Canal Head Power House (CHPH)", units: "5 x 50 MW Kaplan Turbines", totalMw: 250 }
    ],
    operatingHeadMeters: 115.0,
    fullReservoirLevelMeters: 138.68,
    operator: "Sardar Sarovar Narmada Nigam Ltd (SSNNL) / NCA",
    description: "Monumental gravity dam on Narmada River with 1,200 MW underground pumped-storage capable river bed power station. Shared between Gujarat, MP, and Maharashtra.",
    status: "ONLINE",
    curtailed: false,
    corridorTarget: "SNK-AHMEDABAD"
  },
  {
    id: "SRC-TEHRI",
    name: "Tehri Hydro & Pumped Storage Complex",
    location: "New Tehri / Garhwal",
    state: "Uttarakhand",
    riverBasin: "Bhagirathi River",
    coordinates: [30.37, 78.48],
    region: "NR",
    type: "HYDRO_PSP",
    subtype: "Peaking & Pumped Storage Plant",
    capacityMw: 2400,
    currentGenMw: 1450,
    minDispatchMw: 400,
    maxDispatchMw: 2400,
    voltageKv: 400,
    units: [
      { stage: "Tehri Dam HPP", capacityMw: 1000, units: "4 x 250 MW" },
      { stage: "Tehri Pumped Storage (PSP)", capacityMw: 1000, units: "4 x 250 MW Reversible" },
      { stage: "Koteshwar Dam Downstream", capacityMw: 400, units: "4 x 100 MW" }
    ],
    operatingHeadMeters: 231.0,
    operator: "THDC India Limited (NTPC Subsidiary)",
    description: "India's highest dam (260.5m) and primary AGC secondary frequency control asset for the Northern Regional Grid.",
    status: "ONLINE",
    curtailed: false,
    corridorTarget: "SNK-DELHI"
  },
  {
    id: "SRC-KOYNA",
    name: "Koyna Hydroelectric Project",
    location: "Koynanagar / Satara District",
    state: "Maharashtra",
    riverBasin: "Koyna River",
    coordinates: [17.40, 73.75],
    region: "WR",
    type: "HYDRO_DAM",
    subtype: "Underground High-Head Pelton & Francis",
    capacityMw: 1960,
    currentGenMw: 1250,
    minDispatchMw: 200,
    maxDispatchMw: 1960,
    voltageKv: 400,
    units: [
      { stage: "Stage I & II", capacityMw: 560, type: "Pelton Turbines" },
      { stage: "Stage III", capacityMw: 320, type: "Francis Turbines" },
      { stage: "Stage IV", capacityMw: 1000, type: "Underground Francis Turbines" },
      { stage: "Dam Foot HPP", capacityMw: 80, type: "Kaplan Turbines" }
    ],
    operatingHeadMeters: 487.0,
    operator: "Maharashtra State Power Generation Co (Mahagenco)",
    description: "Largest completed hydroelectric facility in India, utilizing steep Western Ghats headdrop to supply peaking power to Mumbai & Pune.",
    status: "ONLINE",
    curtailed: false,
    corridorTarget: "SNK-MUMBAI"
  },

  // --- 2. NUCLEAR POWER PLANTS ---
  {
    id: "SRC-KAKRAPAR",
    name: "Kakrapar Atomic Power Station (KAPS)",
    location: "Vyara / Mandvi / Tapi District (near Surat)",
    state: "Gujarat",
    riverBasin: "Moticher Lake / Tapi Water Canal",
    coordinates: [21.24, 73.35],
    region: "WR",
    type: "NUCLEAR_BASE",
    subtype: "Pressurized Heavy Water Reactor (PHWR)",
    capacityMw: 1840,
    currentGenMw: 1800,
    minDispatchMw: 1600,
    maxDispatchMw: 1840,
    voltageKv: 400,
    units: [
      { unitNo: "KAPS-1", capacityMw: 220, type: "Indigenized PHWR", status: "ONLINE" },
      { unitNo: "KAPS-2", capacityMw: 220, type: "Indigenized PHWR", status: "ONLINE" },
      { unitNo: "KAPS-3", capacityMw: 700, type: "First Indigenous 700MWe PHWR", status: "ONLINE" },
      { unitNo: "KAPS-4", capacityMw: 700, type: "Commercial 700MWe PHWR", status: "ONLINE" }
    ],
    fuelType: "Natural Uranium (UO2) / Heavy Water (D2O)",
    operator: "Nuclear Power Corporation of India Limited (NPCIL)",
    description: "India's landmark nuclear power facility hosting the nation's first twin 700 MWe indigenous PHWR reactors, providing continuous zero-carbon baseload to Western Grid.",
    status: "ONLINE",
    curtailed: false,
    corridorTarget: "SNK-HAZIRA"
  },
  {
    id: "SRC-TARAPUR",
    name: "Tarapur Atomic Power Station (TAPS)",
    location: "Boisar / Palghar District",
    state: "Maharashtra",
    riverBasin: "Arabian Sea Coastal",
    coordinates: [19.83, 72.65],
    region: "WR",
    type: "NUCLEAR_BASE",
    subtype: "BWR & PHWR Nuclear Plant",
    capacityMw: 1400,
    currentGenMw: 1350,
    minDispatchMw: 1200,
    maxDispatchMw: 1400,
    voltageKv: 400,
    units: [
      { unitNo: "TAPS-1 & 2", capacityMw: 320, type: "Boiling Water Reactor (GE USA)" },
      { unitNo: "TAPS-3 & 4", capacityMw: 1080, type: "540 MWe PHWR (NPCIL)" }
    ],
    fuelType: "Enriched Uranium / Natural Uranium",
    operator: "NPCIL",
    description: "Oldest commercial nuclear power station in India (operational since 1969), feeding Mumbai Metropolitan Region and industrial Thane belt.",
    status: "ONLINE",
    curtailed: false,
    corridorTarget: "SNK-MUMBAI"
  },
  {
    id: "SRC-KUDANKULAM",
    name: "Kudankulam Nuclear Power Plant (KKNPP)",
    location: "Radhapuram / Tirunelveli District",
    state: "Tamil Nadu",
    riverBasin: "Gulf of Mannar / Indian Ocean",
    coordinates: [8.17, 77.71],
    region: "SR",
    type: "NUCLEAR_BASE",
    subtype: "VVER-1000 Pressurized Water Reactor",
    capacityMw: 2000,
    currentGenMw: 1980,
    minDispatchMw: 1800,
    maxDispatchMw: 2000,
    voltageKv: 400,
    units: [
      { unitNo: "KKNPP-1", capacityMw: 1000, type: "AES-92 VVER-1000", status: "ONLINE" },
      { unitNo: "KKNPP-2", capacityMw: 1000, type: "AES-92 VVER-1000", status: "ONLINE" }
    ],
    fuelType: "Enriched Uranium (U-235)",
    operator: "NPCIL & Rosatom",
    description: "Highest capacity nuclear generation station in India, generating massive zero-carbon baseload power for Tamil Nadu, Karnataka, and Kerala.",
    status: "ONLINE",
    curtailed: false,
    corridorTarget: "SNK-BLR"
  },

  // --- 3. MEGA SOLAR & RENEWABLE HYBRID PARKS ---
  {
    id: "SRC-BHADLA",
    name: "Bhadla Solar Park",
    location: "Phalodi / Jodhpur District",
    state: "Rajasthan",
    coordinates: [27.53, 71.91],
    region: "NR",
    type: "SOLAR_RE",
    subtype: "Utility-Scale Photovoltaic Park",
    capacityMw: 2245,
    currentGenMw: 1840,
    minDispatchMw: 0,
    maxDispatchMw: 2245,
    voltageKv: 765,
    areaAcres: 14000,
    modulesCount: "10 Million+ PV Panels",
    operator: "RSDCL, NTPC, Adani & Saurya Urja",
    description: "World's largest operational solar park covering 14,000 acres of Thar Desert, feeding the 765 kV Green Energy Corridor to Delhi-NCR.",
    status: "ONLINE",
    curtailed: false,
    corridorTarget: "SNK-DELHI"
  },
  {
    id: "SRC-KHAVDA",
    name: "Khavda Renewable Energy Park",
    location: "Rann of Kutch (Vighakot)",
    state: "Gujarat",
    coordinates: [23.85, 69.73],
    region: "WR",
    type: "HYBRID_RE",
    subtype: "Hybrid Wind-Solar Mega Installation",
    capacityMw: 3000,
    currentGenMw: 2420,
    minDispatchMw: 0,
    maxDispatchMw: 3000,
    voltageKv: 765,
    areaSqKm: 726,
    operator: "Adani Green Energy & NTPC REL",
    description: "Mega hybrid park spanning the salt desert of Rann of Kutch (target 30 GW, currently 3,000 MW operational). Wheels power via 765kV EHV lines to Western & Northern grids.",
    status: "ONLINE",
    curtailed: false,
    corridorTarget: "SNK-MUMBAI"
  },
  {
    id: "SRC-CHARANKA",
    name: "Charanka Solar Park (Gujarat Solar Park-1)",
    location: "Santalpur / Patan District",
    state: "Gujarat",
    coordinates: [23.91, 71.19],
    region: "WR",
    type: "SOLAR_RE",
    subtype: "Multi-Developer Solar Park",
    capacityMw: 790,
    currentGenMw: 680,
    minDispatchMw: 0,
    maxDispatchMw: 790,
    voltageKv: 400,
    areaAcres: 5384,
    operator: "Gujarat Power Corporation Limited (GPCL)",
    description: "Pioneering utility-scale solar park in India, commissioned in 2012 across semi-arid wasteland in Patan. Major contributor to Gujarat green power wheeling.",
    status: "ONLINE",
    curtailed: false,
    corridorTarget: "SNK-AHMEDABAD"
  },
  {
    id: "SRC-PAVAGADA",
    name: "Pavagada Solar Park (Shakti Sthala)",
    location: "Pavagada / Tumakuru District",
    state: "Karnataka",
    coordinates: [14.10, 77.27],
    region: "SR",
    type: "SOLAR_RE",
    subtype: "Utility-Scale Photovoltaic Park",
    capacityMw: 2050,
    currentGenMw: 1710,
    minDispatchMw: 0,
    maxDispatchMw: 2050,
    voltageKv: 400,
    areaAcres: 13000,
    operator: "Karnataka Solar Power Development Corp (KSPDCL)",
    description: "World-class solar park deployed across drought-prone land in Karnataka, powering Bengaluru's electronics and tech manufacturing belts.",
    status: "ONLINE",
    curtailed: false,
    corridorTarget: "SNK-BLR"
  },
  {
    id: "SRC-MUPPANDAL",
    name: "Muppandal Wind Energy Complex",
    location: "Aralvaimozhi / Kanyakumari District",
    state: "Tamil Nadu",
    coordinates: [8.26, 77.54],
    region: "SR",
    type: "WIND_RE",
    subtype: "Onshore Wind Turbine Farm",
    capacityMw: 1500,
    currentGenMw: 1120,
    minDispatchMw: 100,
    maxDispatchMw: 1500,
    voltageKv: 400,
    turbinesCount: "3,000+ Wind Turbines",
    operator: "Tamil Nadu Generation and Distribution Corp (TANGEDCO)",
    description: "Historic high-capacity wind farm corridor capturing intense seasonal southwest monsoonal winds funnelled through the Western Ghats mountain pass.",
    status: "ONLINE",
    curtailed: false,
    corridorTarget: "SNK-CHENNAI"
  },

  // --- 4. SUPER THERMAL BASELOAD POWER STATIONS ---
  {
    id: "SRC-SINGRAULI",
    name: "Singrauli Super Thermal Power Station (NTPC)",
    location: "Shaktinagar / Sonebhadra District",
    state: "Uttar Pradesh",
    coordinates: [24.10, 82.67],
    region: "NR",
    type: "THERMAL_COAL",
    subtype: "Pithead Super Thermal Power Plant",
    capacityMw: 2000,
    currentGenMw: 1880,
    minDispatchMw: 1100,
    maxDispatchMw: 2000,
    voltageKv: 500,
    units: "5 x 200 MW + 2 x 500 MW Supercritical Boilers",
    fuelSource: "Northern Coalfields Limited (NCL) Jayant / Dudhichua",
    operator: "NTPC Limited",
    description: "Pioneering NTPC thermal station connected via India's first ±500 kV HVDC Rihand-Dadri transmission link directly to Delhi-NCR.",
    status: "ONLINE",
    curtailed: false,
    corridorTarget: "SNK-DELHI"
  },
  {
    id: "SRC-MUNDRA",
    name: "Mundra Thermal Power Station",
    location: "Mundra Port / Kutch",
    state: "Gujarat",
    coordinates: [22.82, 69.52],
    region: "WR",
    type: "THERMAL_COAL",
    subtype: "Coastal Supercritical Coal Plant",
    capacityMw: 4620,
    currentGenMw: 3950,
    minDispatchMw: 2200,
    maxDispatchMw: 4620,
    voltageKv: 500,
    units: "4 x 330 MW Subcritical + 5 x 660 MW Supercritical",
    fuelSource: "Imported Coal via Mundra Capesize Deepwater Berth",
    operator: "Adani Power & Tata Power (CGPL)",
    description: "One of the world's largest coal-fired generation hubs, connected to Haryana via the ±500 kV HVDC Mundra-Mohindergarh link and to Gujarat grid.",
    status: "ONLINE",
    curtailed: false,
    corridorTarget: "SNK-SANAND"
  },
  {
    id: "SRC-WANAKBORI",
    name: "Wanakbori Thermal Power Station (WTPS)",
    location: "Wanakbori / Kheda District",
    state: "Gujarat",
    riverBasin: "Mahi River",
    coordinates: [22.88, 73.36],
    region: "WR",
    type: "THERMAL_COAL",
    subtype: "Inland Supercritical Coal Power Station",
    capacityMw: 2270,
    currentGenMw: 1920,
    minDispatchMw: 1000,
    maxDispatchMw: 2270,
    voltageKv: 400,
    units: "7 x 210 MW + 1 x 800 MW Supercritical Unit #8",
    operator: "Gujarat State Electricity Corporation Limited (GSECL)",
    description: "Major base-load coal-fired station on the banks of Mahi river, providing critical grid stability to central Gujarat industrial corridors.",
    status: "ONLINE",
    curtailed: false,
    corridorTarget: "SNK-AHMEDABAD"
  }
];

export const SOURCE_TYPE_METRICS = {
  HYDRO_DAM: { color: "#38bdf8", icon: "💧", label: "Hydroelectric Dam" },
  HYDRO_PSP: { color: "#0ea5e9", icon: "🔄", label: "Pumped Storage Hydro" },
  NUCLEAR_BASE: { color: "#a855f7", icon: "⚛️", label: "Nuclear Power" },
  SOLAR_RE: { color: "#f59e0b", icon: "☀️", label: "Solar PV Park" },
  HYBRID_RE: { color: "#06b6d4", icon: "🌤️", label: "Wind-Solar Hybrid" },
  WIND_RE: { color: "#10b981", icon: "💨", label: "Onshore Wind Complex" },
  THERMAL_COAL: { color: "#8b5cf6", icon: "🏭", label: "Super Thermal Coal" }
};
